# **파이썬 머신러닝 완벽 가이드(개정2판)**
#### 권철민 저, 위키북스
## **01 파이썬 기반의 머신러닝과 생태계 이해**

### **03 넘파이**
#### **넘파이 ndarray 개요**

In [1]:
import numpy as np

**ndarray** : numpy의 기반 데이터 타입  
**np.array()** : 인자를 ndarray로 변환해 반환  
**ndarray.shape** : (row #, col #)

In [2]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)  # 1차원 array, 3개의 data 

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)  # 2차원 array, 6개의 data

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)  # 2차원 array, 3개의 data

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


#### <br/>**ndarray의 데이터 타입**  
<br/>ndarray내의 데이터 값은 숫자, 문자열, 불 값 등 모두 가능  
int(8bit, 16bit, 32bit), unsigned int(8bit, 16bit, 32bit), float(16bit, 32bit, 64bit, 128bit), coplex 가능  
ndarray 내의 데이터 타입은 같은 데이터 타입만 가능 (한 개의 ndarray 객체에 int와 float 동시 사용 불가)  
**ndarray.dtype** : ndarray 내의 데이터 타입 확인

In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


<br/>다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경할 경우 데이터 크기가 더 큰 데이터 타입으로 일괄 형 변환

In [5]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)  # int형이 유니코드 문자열 값으로 변환됨

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)  # int형이 float64형으로 변환됨

['1' '2' 'test'] <U11
[1. 2. 3.] float64


<br/> **astype()** : ndarray 내 데이터값의 타입 변경  
대용량 데이터의 ndarray를 만들 때 메모리 절약

In [6]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


#### <br/>**ndarray를 편리하게 생성하기 - arange, zeros, ones**

<br/> **arange()** : array를 range()로 표현하는 것 (default 함수 인자는 stop 값, start 값도 부여 가능)

In [7]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


<br/>**zeros()** : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape을 가진 ndarray 반환  
**ones()** : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1으로 채운 해당 shape을 가진 ndarray 반환  
함수 인자로 dtype을 정해주지 않으면 default로 float64형의 데이터로 ndarray를 채움

In [8]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#### <br/> **ndarray의 차원과 크기를 변경하는 reshape()**  
<br/>**reshape()** : ndarray를 특정 차원 및 크기로 변환, 변환을 원하는 크기를 함수 인자로 부여  
인자 튜플의 요소의 개수 = 차원

In [9]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


<br/>지정된 사이즈로 변경이 불가능하면 오류 발생

In [10]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

<br/>-1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환

In [11]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)  # 고정된 5개의 columns에 맞는 row를 자동으로 생성 -> 2x5=10
print('arrau2 shape:', array2.shape)
array3 = array1.reshape(5,-1)  # 고정된 5개의 rows에 맞는 columns를 자동으로 생성(2) -> 2x5=10
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
arrau2 shape: (2, 5)
array3 shape: (5, 2)


<br/>호환될 수 없는 형태는 변환 불가

In [12]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

<br/> **reshape(-1,1)** : 원본 ndarray가 어떤 형태이든 1개의 column을 가진 2차원 ndarray로 변환  
여러 개의 넘파이 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray의 형태를 통일해 유용하게 사용 가능  
**tolist()** : ndarray를 list 자료형으로 변환 (아래로 너무 길어지면 보기 불편하니까)

In [13]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))  # 3차원 ndarray로 변환
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


#### <br/> **넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)**  
1. **특정한 데이터만 추출** : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터 반환
2. **슬라이싱(Slicing)** : 연속된 인덱스상의 ndarray를 추출. '시작 인덱스 : 종료 인덱스' -> 시작 인덱스부터 종료 인덱스-1까지에 해당하는 ndarray 반환
3. **팬시 인덱싱(Fancy Indexint)** : 일정한 인덱싱 집합을 list 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray 반환
4. **불린 인덱싱(Boolean Indexing)** : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환

<br/> **단일 값 추출**

ndarray[i] : i+1번째 인덱스 위피의 데이터값

In [14]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작하므로 array1[2]는 3번쩨 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


<br/>ndarray[-1] : 맨 뒤의 데이터값  
ndarray[-2] : 맨 뒤에서 두 번째의 데이터값

In [15]:
print('맨 뒤의 값:', array1[-1], ' 맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9  맨 뒤에서 두 번째 값: 8


<br/>단일 인덱스를 이용해 ndarray 내의 데이터값 수정 가능

In [16]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


<br/>다차원 ndarray에서 단일 값 추출 [row, col]  
numpy에서는 row, column 사용되지 않음  
>**axis 0** = row 방향 축  
>**axis 1** = column 방향 축  
>[row = 0, col = 1] = [axis 0 = 0, axis1 = 1]

n차원 ndarray는 n개의 axis 가짐

In [17]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


<br/>**슬라이싱**  
<br/>'시작 인덱스 **:** 종료 인덱스' 기호를 이용해 연속한 데이터를 슬라이싱해서 추출
시작 인덱스 ~ 종료 인덱스-1의 위치에 있는 ndarray 반환
단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입

In [18]:
array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


<br/>':' 사이의 시작, 종료 인덱스는 생략 가능  
1. 시작 인덱스 생략 : 자동으로 맨 처음 인덱스인 0으로 간주
2. 종료 인덱스 생략 : 자동으로 맨 마지막 인덱스로 간주
3. 시작/종료 인덱스 생략 : 자동으로 맨 처음/마지막 인덱스로 간주 

In [19]:
array1 = np.arange(1,10)
array4 = array1[:3]   # 0 ~ 2
print(array4)

array5 = array1[3:]   # 3 ~ 8
print(array5)

array6 = array1[:]    # 0 ~ 8
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


<br/>2차원 ndarray에서 슬라이싱으로 데이터에 접근  
콤마(,)로 row와 column 인덱스를 지칭

In [20]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])  # row와 column 축 한쪽에만 슬라이싱 적용, 다른 쪽 축에는 단일 값 인덱스 적용

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


<br/> 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환함

In [21]:
print('array2d[0]:', array2d[0])  # row축(asix 0)의 첫 번쨰 row ndarray(1차원) 반환
print('array2d[1]:', array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

array2d[0]: [1 2 3]
array2d[1]: [4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


<br/>**팬시 인덱싱**  
<br/>리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray 반환

In [22]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]  # row축에 팬시 인덱싱 [0,1] 적용, column축에 단일 값 인덱싱 2 적용, (row,col) 인덱스가 (0,2),(1,2)로 적용됨
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1], 0:2]  # ((0,0),(0,1),((1,0),(1,1)) 인덱싱 적용
print('array2d[[0,1],] 0:2] =>', array4.tolist())

array5 = array2d[[0,1]]  # ((0,:),(1,:)) 인덱싱 적용
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],] 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


<br/> **불린 인덱싱**  
<br/>조건 필터링과 검색 동시에 수행 가능  
조건문과 반복문보다 훨씬 간단!  
[ ] 내에 조건문 그대로 기재

In [23]:
array1d = np.arange(1,10)
# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


<br/>내부 로직
>**1.** array1d > 5와 같이 ndarray의 필터링 조건을 [ ] 안에 기재  
>**2.** False 값은 무시하고 True값에 해당하는 인덱스 값만 저장 (단, True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장)  
>**3.** 저장된 인덱스 데이터 세트로 ndarray 조회

In [24]:
array1d > 5  # ndarray 객체에 조건식 할당시 False, True로 이루어진 ndarray 객체 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [25]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])  # 인덱스 [5,6,7,8]
array3 = array1d[boolean_indexes]  # array1d[[5,6,7,8]] = [6,7,8,9]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [26]:
# 아래와 같이 직접 인덱스 집합을 만들어 대입한 것과 동일
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


#### <br/> **행렬의 정렬 - sort()와 argsort()**  
<br/>**행렬 정렬**  
<br/>**np.sort()** : 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
<br/>**ndarray.sort()** : 원 행렬 자체를 정렬한 형태로 반환, 반환 값은 None  

In [27]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)
# np.sort로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 행렬 정렬:', sort_array1)
print('np.sort() 호풀 후 원본 행렬:', org_array)
# ndarray.sort() 로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 행렬 정렬: [1 3 5 9]
np.sort() 호풀 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


<br/>기본적으로 np.sort()와 ndarray.sort() 모두 오름차운으로 행렬 내 원소를 정렬  
내림차순으로 정렬할 때는 [::-1] 적용

In [28]:
sort_array1_desc = np.sort(org_array)[::-1]  # 내림차순 적용
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


<br/>행렬이 2차원 이상인 경우 axis 축 값 설정으로 통해 row 방향 또는 colmn 방향으로 정렬을 수행

In [29]:
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)  # row 방향으로 정렬
print('row 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)  # column 방향으로 정렬
print('column 방향으로 정렬:\n', sort_array2d_axis1)

row 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
column 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


<br/>**정렬된 행렬의 인덱스를 반환하기**  
<br/>**np.argsort()** : 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환  
np.argsort(A) 호출 &rarr; 정렬된 행렬의 원본 행렬 인덱스 추출 &rarr; 정렬된 원본의 원본 행렬 인덱스 반환

In [30]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


<br/>내림차순으로 정렬 시 원본 행렬의 인덱스를 구할 때 [::-1] 적용

In [31]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


<br/>넘파이의 ndarray는 RDBMS의 TABLE column이나 판다스 DataFrame column과 같은 메타 데이터를 가질 수 없음  
&rarr; 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 가져야 함

In [32]:
# 학생별 시험 성적 데이터
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])  # 학생 이름 ndarray
score_array = np.array([78,95,84,98,88])  # 학생 성적 ndarray

# 시험 성적순으로 학생 이름을 출력
sort_indices_asc = np.argsort(score_array)  # 인덱스 반환
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])  # 반환된 인덱스를 name_array에 팬시 인덱스로 적용해 데이터 추출

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


#### <br/>**선형대수 연산 - 연산 행렬 내적과 전치 행렬 구하기**  
<br/>**행렬 내적(행렬 곱)**  
<br/>**np.dot(A, B)** : 왼쪽 행렬의 row와 오른쪽 행렬의 column들의 원소들을 순차적으로 곱한 뒤 그 숫자를 모두 더함

In [33]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


<br/>**전치 행렬**  
<br/>**transpose()** : 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 전치 행렬 반환

In [34]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
