In [3]:
import numpy as np #넘파이 모듈 임포트(약어 사용)

In [6]:
array1 = np.array([1,2,3]) #np.array()함수는 다양한 인자를 입력받아 ndarray로 변환 수행
#1차원 array
print('array1.type:', type(array1)) #type함수로 array1의 데이터타입 확인
print('array1 array 형태:', array1.shape) #ndarray 배열의 shape변수는 행과 열의 수를 튜플 형태로 가지고 있다. 이를 통해 차원 확인

array2 = np.array([[1,2,3],
                   [4,5,6]])
#2차원 array, 2개의 행과 3개의 열
print('array2.type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
#2차원 array, 1개의 행과 3개의 열 (array1과 다르다)
print('array3.type:', type(array3))
print('array3 array 형태:', array3.shape)

array1.type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2.type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3.type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [8]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))
#array1은 1차원, array3은 2차원

array1: 1차원, array2: 2차원, array3: 2차원


In [12]:
#ndarray 데이터 타입
#ndarray의 데이터값은 숫자, 문자열, bool 모두 가능하나 같은 데이터 타입만 가능
list1 = [1,2,3] #모두 int형
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype) #모두 int32형태

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [13]:
list2 = [1,2,'test'] #int형과 str형이 섞인 리스트
array2 = np.array(list2)
print(array2, array2.dtype) #데이터 타입이 달라 더 큰 데이터타입인 유니코드 문자열 값으로 변환

list3 = [1,2,3.0] #int형과 float형이 섞인 리스트
array3 = np.array(list3)
print(array3, array3.dtype) #마찬가지로 int형 데이터가 float형으로 변환

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [15]:
#astype()메서드를 이용해 데이터타입 변경
array_int = np.array([1,2,3])
array_float = array_int.astype('float64') #int형 데이터를 float형으로 변경
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32') #float형 데이터를 int형으로 변경
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1]) 
array_int2 = array_float1.astype('int32') #float형 데이터를 int형으로 변경
print(array_int2, array_int2.dtype) #이때 소수점 이하는 사라잠

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [18]:
#ndarray생성 - arange, zeros, ones

#np.arange: range와 유사한 기능, 0부터 인자값-1 까지 순차적으로 ndarray 데이터값으로 변환
sequence_array = np.arange(10) #0부터 9까지 연속 숫자값을 가지는 ndarray
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
#range와 유사하게 start값을 부여할 수 있다

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [20]:
#np.zeros: 인자로 튜플 형태의 shape값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환
#np.ones: 유사하게 모든 값을 1로 채운 ndarray 반환
zero_array = np.zeros((3,2), dtype = 'int32') #3*2 shape의 모든 값이 0인 ndarray
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2)) #3*2 shape의 모든 값이 1인 ndarray
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [23]:
#reshape: ndarray 차원과 크기 변경
array1 = np.arange(10) #0부터 9까지 값을 가지는 ndarray
print('array1:\n', array1)

array2 = array1.reshape(2,5) #2*5 형태 2차원 ndarray로 변환
print('array2:\n', array2)

array3 = array1.reshape(5,2) #5*2 형태 2차원 ndarray로 변환
print('array3\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [24]:
array1.reshape(4,3) #지정된 사이즈로 변경 불가능시 오류 발생

ValueError: cannot reshape array of size 10 into shape (4,3)

In [25]:
array1 = np.arange(10)
print(array1)
#reshape인자에 -1을 적용하면 원래 ndarray와 호환되는 새로운 shape로 변환
array2 = array1.reshape(-1,5) #고정된 5개의 열과 호환되는 2개의 행을 지닌 2차원 ndarray로 변환
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1) #고정된 5개의 행과 호환되는 2개의 열을 지닌 2차원 ndarray로 변환
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [26]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) #물론 호환될 수 없는 형태는 변환 불가

ValueError: cannot reshape array of size 10 into shape (4)

In [28]:
#-1인자는 reshape(1,-1) 같은 형태로 자주 사용
#원본 ndarray가 어떤 형태라도 2차원이고 반드시 1개의 컬럼을 가진 ndarray로 변환을 보장함
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [29]:
#ndarray 인덱싱
#특정 데이터 추출, 슬라이싱, 팬시인덱싱, 불린인덱싱
#단일 값 추출
#1부터 9까지의 1차원 ndarray
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [30]:
#인덱스에 마이너스 기호 사용하면 맨뒤에서부터 데이터 추출가능
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [31]:
#단일 인덱스를 이용해 ndarray 내의 데이터값도 간단히 수정 가능
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [38]:
#다차원 ndarray에서 값 추출
#콤마로 구분된 행(axis 0)과 열(axis 1) 인덱스를 통해 접근
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0]) #행 인덱스:0, 열 인덱스:0 인 값
print('(row=0, col=1) index 가리키는 값:', array2d[0,1]) #행 인덱스:0, 열 인덱스:1 인 값
print('(row=1, col=0) index 가리키는 값:', array2d[1,0]) #행 인덱스:1, 열 인덱스:0 인 값
print('(row=2, col=2) index 가리키는 값:', array2d[2,2]) #행 인덱스:2, 열 인덱스:2 인 값

#axis 0이 행 방향, axis 1이 열 방향임을 이해하자

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [39]:
#슬라이싱
#':' 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스부터 종료 인덱스 -1 위치에 있는 데이터의 ndarray 반환
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [40]:
#:기호의 시작, 종료 인덱스는 생략 가능
#:기호 앞 인덱스 생략시 자동으로 0으로 간주
#:기호 뒤 인덱스 생략시 자동으로 맨 마지막 인덱스로 간주
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [43]:
#2차원 ndarray 슬라이싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2]) #행 인덱스:0~1, 열 인덱스: 0~1에 해당하는 값
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3]) #행 인덱스:1~2, 열 인덱스: 0~2에 해당하는 값
print('array2d[1:3, :] \n', array2d[1:3, :]) #행 인덱스:1~2, 열 인덱스 전체에 해당하는 값
print('array2d[:, :] \n', array2d[:, :]) #행 인덱스 전체, 열 인덱스 전체에 해당하는 값
print('array2d[:2, 1:] \n', array2d[:2, 1:]) #행 인덱스:0~1, 열 인덱스: 1~마지막에 해당하는 값
print('array2d[:2, 0] \n', array2d[:2, 0]) #행 인덱스:0~1, 열 인덱스: 0에 해당하는 값

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [44]:
#2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray 반환
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [46]:
#팬시 인덱싱
#리스트나 ndarray로 인덱스 집합을 지정해 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방법
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2] #행, 열 인덱스가 (0,2), (1,2)로 적용
print('array2d[[0,1], 2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2] #행, 열 인덱스가 ( (0,0), (0,1) ), ( (1,0),(1,1) )로 적용
print('array2d[[0,1], 0:2] => ', array4.tolist())

array5 = array2d[[0,1]] #행, 열 인덱스가 ( (0,:), (1,:) )로 적용
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


In [47]:
#불린 인덱싱
#조건 필터링, 검색을 동시에 가능
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 (조건) boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과:', array3)

array1d > 5 불린 인덱싱 결과: [6 7 8 9]


In [49]:
#ndarray객체에 조건식 할당
array1d > 5
#True, False로 이루어진 ndarray객체 반환
#이 ndarray 객체를 []안에 입력하면 False값은 무시하고 True값이 있는 위치 인덱스값으로 자동 변환해 해당 위치의 데이터만 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [51]:
#동일한 불린 ndarray를 만들고 array1d[]내에 인덱스로 입력해보기
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3) #동일한 결과 출력

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [54]:
#다음과 같이 직접 인덱스 집합을 만들어 대입한 것과 동일
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

#불린 인덱싱 동작 단계
#1. ndarray의 필터링 조건을 []안에 입력
#2. True값에 해당하는 인덱스값만 저장 (True값을 가진 인덱스 저장)
#3. 저장된 인덱스 데이터 세트로 ndarray 조회

일반 인덱스로 필터링 결과 : [6 7 8 9]


In [6]:
#행렬 정렬
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
#np.sort()는 원본 행렬을 변경하지 않고 정렬된 형태로 반환한다
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
#ndarray.sort()는 원본 행렬 자체를 변경한다
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [7]:
#내림차순으로 정렬하기 위해 [::-1]와 같이 사용한다
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [14]:
#행렬이 2차원 이상일 경우 축 값 설정을 통해 로우/칼럼 방향 정렬 수행 가능
array2d = np.array([[8,12],
                   [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0) #axis0(로우) 방향 정렬
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1) #axis1(칼럼) 방향 정렬
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [15]:
#np.argsort(): 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [16]:
#내림차순 정렬 시 원본 행렬 인덱스 구하기
#[::-1] 적용
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [18]:
#넘파이 ndarray는 판다스 DataFrame 등과 다르게 메타 데이터를 가질 수 없다
#따라서 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 지정해야 한다
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
#score_array에서 성적 순서를 나타내는 인덱스를 추출해서
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
#그 인덱스를 name_array 팬시 인덱스로 적용하여 성적 순 이름을 구한다
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [23]:
#선형대수 연산
#행렬 내적(행렬 곱) - np.dot()
#행렬 내적이란?
#왼쪽 행렬(A)의 행과 오른쪽 행렬(B)의 열의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
#왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 일치해야한다
dot_product = np.dot(A,B)
#A와 B의 행렬 내적을 계산한다
print('행렬의 내적 결과:\n', dot_product)

행렬의 내적 결과:
 [[ 58  64]
 [139 154]]


In [26]:
#전치 행렬 -  np.transpose()
#원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
#2*2 행렬의 경우 1행2열의 원소를 2행1열로, 2행1열의 원소를 1행2열로 교환
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)
#1행 2열의 원소(2)가 2행 1열로, 2행 1열의 원소(3)이 1행 2열로 교환된 것을 볼 수 있다

A의 전치 행렬:
 [[1 3]
 [2 4]]


In [27]:
#pandas
import pandas as pd

In [30]:
#titanic_train 파일의 경로를 이용해 read_csv()로 읽기
titanic_df = pd.read_csv(r"C:\Users\motor\coding\titanic_train.csv")
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [34]:
#주피터노트북과 csv파일이 같은 디렉토리에 있으면 csv파일 이름만으로 호출 가능
titanic_df = pd.read_csv('titanic_train.csv')
print('titanic 변수 type:', type(titanic_df))
titanic_df

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [37]:
#DataFrame.head()는 데이터프레임 맨 위 n개의 행을 반환
#기본값: 5
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [38]:
#데이터프레임 행,열 크기 알아보기
#shape는 데이터프레임 행,열을 튜플 형태로 반환
print('DataFrame 크기: ', titanic_df.shape)

DataFrame 크기:  (891, 12)


In [41]:
#데이터프레임 정보 조회 - info(), describe()
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [44]:
#describe()는 오직 숫자형(int, float) 칼럼의 분포도만 조사
titanic_df.describe()
#count: 데이터 건수, mean: 평균, std: 표준편차, min: 최솟값,  n%: n pecentile 값,  max: 최댓값

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [47]:
#value_count(): 데이터의 분포도를 확인하는데 매우 유용
#데이터프레임의 []연산자 내에 칼럼명 입력시 시리즈 형태로 특정 칼럼 데이터 세트가 반환
value_counts = titanic_df['Pclass'].value_counts()
#Pclass 칼럼의 유형과 건수를 확인할 수 있다
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [48]:
#데이터프레임의 []연산자 내에 칼럼명 입력시 시리즈 형태로 특정 칼럼 데이터 세트가 반환
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


In [50]:
#series: 하나의 칼럼으로 구성된 데이터셋
titanic_pclass.head()
#인덱스와 칼럼 데이터값으로 구성

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [53]:
#단일 칼럼으로 되어 있는 시리즈 객체에서 value_count()를 호출하는 것이 파악하기 쉬움
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)
#시리즈 인덱스의 고유성이 보장된다면 의미있는 데이터 값도 할당 가능

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [55]:
#value_counts()는 기본적으로 dropna가 True로 지정되어있다
print('titanic_df 데이터 건수:', titanic_df.shape[0])
print('기본 설정인 dropna=True로 value_counts()')
#value_counts()는 디폴트로 dropna=True이므로 value_counts(dropna=True)와 동일
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False))
#dropna인자를 False로 지정해 NA값 또한 value_counts()에 포함시킴

titanic_df 데이터 건수: 891
기본 설정인 dropna=True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64


In [56]:
#ndarray, list, dictionary -> DataFrame
col_name1 = ['col1']
list1 = [1,2,3]
array1 = np.array(list1)
print('array1.shape:', array1.shape)
#리스트를 이용해 DataFrame 생성
df_list1 = pd.DataFrame(list1, columns = col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)
#넘파이 ndarray를 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1, columns = col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1.shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [59]:
#2차원 데이터 기반 DataFrame 생성
#2*3형태의 데이터를 기반으로 생성할 것이므로 columns 이름이 3개 필요
col_name2 = ['col1','col2','col3']
#2*3 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환
list2 = [[1,2,3],
         [11,12,13]]
array2 = np.array(list2)
print('array2 shape:', array2.shape)
df_list2 = pd.DataFrame(list2, columns = col_name2)
print('2차원 리스트로 만든 DataFrame\n', df_list2)
df_array2 = pd.DataFrame(array2, columns = col_name2)
print('2차원 ndarray로 만든 DataFrame\n', df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame
    col1  col2  col3
0     1     2     3
1    11    12    13


In [63]:
#딕셔너리->DataFrame
#딕셔너리의 key값은 칼럼명, value는 키에 해당하는 칼럼 데이터로 변환
#따라서 key의 경우는 문자열, value의 경우는 리스트 혹은 ndarray형태로 딕셔너리 구성

#key는 문자열 칼럼명으로 매핑, value는 리스트 형(또는 ndarray) 칼럼 데이터로 매핑
dict = {'col1':[1,11], 'col2':[2,22], 'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)
#dict의 key값이 칼럼명, value값이 각 칼럼의 데이터로 매핑

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


In [65]:
#DataFrame->ndarray, list, dictionary
#DataFrame을 ndarray로 변환 : DataFrame 객체의 values 이용
array3 = df_dict.values
#array3의 데이터타입은 ndarray가 되었다
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [70]:
#DataFrame->list : valuse로 얻은 ndarray에 tolist() 호출
#DataFrame을 리스트 형으로 변환
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)

#DataFrame->dictionary : DataFrame 객체의 to_dict()메서드로 호출
#인자로 'list'입력 시 딕셔너리 값이 리스트형으로 반환|
#DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [73]:
#데이터프레임 칼럼 데이터 세트 생성과 수정
#[]연산자 활용
titanic_df['Age_0'] = 0 #새로운 Age_0 칼럼을 추가하고 일괄적으로 0값을 할당
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [76]:
#기존 칼럼 series 데이터를 이용해 새로운 칼럼 series 만들기\
#Age값에 10을 곱한  Age_by_10
titanic_df['Age_by_10'] = titanic_df['Age']*10
#Sibsp와 Parch값을 더한 Family_No
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   

   Family_No  
0          2  
1          2  
2          1

In [78]:
#업데이트
#업데이트를 원하는 칼럼 series를 DataFrame[]내에 칼럼명으로 입력한 뒤 값을 할당
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100 #기존값 +100으로 수정
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      420.0   
1      0          PC 17599  71.2833   C85        C      0      580.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      460.0   

   Family_No  
0          2  
1          2  
2          1

In [80]:
#DataFrame 데이터 삭제
#drop()
#DataFrame.drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')
#labels, axis, inplace 파라미터 중요
#주로 axis=1을 이용해 특정 칼럼을 드랍한다
titanic_drop_df = titanic_df.drop('Age_0', axis=1) #'Age_0'칼럼 드랍
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S      420.0          2  
1      0          PC 17599  71.2833   C85        C      580.0          2  
2      0  STON/O2. 3101282   7.9250   NaN        S      460.0          1

In [82]:
#inplace
titanic_df.head(3)
#삭제되었다고 생각한 'Age_0'칼럼이 존재?

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      420.0   
1      0          PC 17599  71.2833   C85        C      0      580.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      460.0   

   Family_No  
0          2  
1          2  
2          1

In [85]:
#drop()에서 inplace=False로 지정하면 삭제된 결과의 DataFrame을 반환함
#inplace=True로 지정하면 자신의 DataFrame의 데이터를 삭제함
#여러개의 칼럼을 리스트 형태로 지정해 여러 칼럼 삭제 가능
drop_result = titanic_df.drop(['Age_0','Age_by_10','Family_No'], axis=1, inplace=True)
print('inplace=True로 drop 후 반환된 값:', drop_result)
titanic_df.head(3)

KeyError: "['Age_0', 'Age_by_10', 'Family_No'] not found in axis"

In [91]:
#axis=0으로 지정해 index=0,1,2 삭제
pd.set_option('display.width', 100)
pd.set_option('display.max_colwidth', 15)
print('#### before axis 0 drop ####')
print(titanic_df.head(3))

titanic_df.drop([0,1,2], axis=0, inplace=True)

print('#### after axis 0 drop ####')
print(titanic_df.head(3))
#index 0,1,2에 위치한 로우가 삭제됨

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare  \
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000   
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   

  Cabin Embarked  
3  C123        S  
4   NaN        S  
5   NaN        Q  


KeyError: '[0, 1, 2] not found in axis'

In [92]:
#index 추출
#DataFrame.index or Series.index 속성을 통해 가능

#원본 파일 다시 로딩
titanic_df = pd.read_csv('titanic_train.csv')
#Index 객체 추출
indexes = titanic_df.index
print(indexes)
#Index 객체를 실제 값 array로 변환
print('Index 객체 array 값:\n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array 값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 23

In [93]:
#Index는 ndarray와 유사하게 단일 값 반환 및 슬라이싱도 가능
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [94]:
#하지만 한 번 만들어진 Index 객체는 함부로 변경 불가능
indexes[0] = 5

TypeError: Index does not support mutable operations

In [95]:
#Series에서 Index는 오직 식별용으로만 사용
series_fair = titanic_df['Fare']
print('Fair Series max 값:', series_fair.max())
print('Fair Series sum 값:', series_fair.sum())
print('sum() Fair Series:', sum(series_fair))
print('Fair Series + 3\n', (series_fair + 3).head(3))

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.949299999967
Fair Series + 3
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [98]:
#DataFarme 및 시리즈에 reset_index() 수행 시 인덱스를 연속 숫자 형으로 할당
#기존 index는 'index'라는 새로운 칼럼명으로 추가
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)
#reset_index()는 인덱스가 연속된 int형 숫자 데이터가 아닐 때 주로 사용

index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  \
0      0            1         0       3  Braund, Mr....    male  22.0      1      0   
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0   
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0   

           Ticket     Fare Cabin Embarked  
0       A/5 21171   7.2500   NaN        S  
1        PC 17599  71.2833   C85        C  
2  STON/O2. 31...   7.9250   NaN        S

In [103]:
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:', type(value_counts))
new_value_counts = value_counts.reset_index(inplace=False)
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:', type(new_value_counts))
#series에 reset_index() 적용 시 기존 인덱스가 칼럼으로 추가돼 DataFrame이 반환됨
#reset_index()의 파라미터 중 drop=True로 설정하면 기존 인덱스는 사라짐

### before reset_index ###
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### After reset_index ###
   Pclass  count
0       3    491
1       1    216
2       2    184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>


In [106]:
print('단일 칼럼 데이터 추출:\n', titanic_df['Pclass'].head(3))
print('\n여러 칼럼의 데이터 추출:\n', titanic_df[['Survived','Pclass']].head(3))
print('[ ]안에 숫자 index는 KeyError 오류 발생:\n', titanic_df[0])
#DataFrame 뒤의 []에 칼럼명이 아닌 값을 지정했기 때문에 오류가 발생한다

단일 칼럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3


KeyError: 0

In [110]:
#판다스의 인덱스 형태로 변환 가능한 표현식은 []안에 입력 가능
#슬라이싱 사용
titanic_df[0:2]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare  \
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   

  Cabin Embarked  
0   NaN        S  
1   C85        C

In [116]:
#불린 인덱싱 가능
titanic_df[titanic_df['Pclass'] == 3].head(3) #'Pclass'값이 3인 행만 추출(3개만)

#데이터프레임 뒤 [] 사용 가이드
#1. 데이터프레임 뒤 []는 넘파이 []나 시리즈 []와 다르다
#2. 데이터프레임 뒤 [] 내 입력값은 칼럼명을 지정해 칼럼 지정 연산 사용하거나 불린 인덱스 용도로만 사용
#3. DataFrame[0:2]와 같은 슬라이싱 연산으로 데이터를 추출하는 방법은 사용하지 않는 것이 좋다

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket  \
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   

    Fare Cabin Embarked  
0  7.250   NaN        S  
2  7.925   NaN        S  
4  8.050   NaN        S

In [117]:
#iloc[] 연산자
#iloc[]: 위치(location) 기반 인덱싱
#행과 열 위치를 0을 출발점으로 하는 세로,가로 축 좌표 정숫값으로 지정하는 방식
data = {'Name':['Chulmin','Eunkyung','Jinwoong','Soobeom'],
        'Year':[2011,2016,2015,2015],
        'Gender':['Male','Female','Male','Male']}
data_df = pd.DataFrame(data, index = ['one','two','three','four'])
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [121]:
data_df.iloc[0,0] #row index 0, columns index 0 인 값(Chulmin) 을 가져온다

'Chulmin'

In [122]:
#iloc[]에 인덱스값이나 칼럼명을 입력하면 오류 발생
#아래 코드는 오류 발생
data_df.iloc[0, 'Name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [123]:
#아래 코드는 오류 발생
data_df.iloc['one',0]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [130]:
#iloc[]의 열 위치에 -1을 입력해 데이터프레임 가장 마지막 열 데이터를 가져오는데 자주 사용
#맨 마지막 칼럼 값 가져옴(타깃 값)
print('\n 맨 마지막 칼럼 데이터 [:, -1] \n', data_df.iloc[:, -1])
#맨 마지막 칼럼 값을 제외한 모든 칼럼 값을 가져옴(피쳐 값)
print('\n 맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1] \n', data_df.iloc[:, :-1])

#iloc는 불린 인덱싱은 제공하지 않음


 맨 마지막 칼럼 데이터 [:, -1] 
 one        Male
two      Female
three      Male
four       Male
Name: Gender, dtype: object

 맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1] 
            Name  Year
one     Chulmin  2011
two    Eunkyung  2016
three  Jinwoong  2015
four    Soobeom  2015


In [132]:
#loc[] 연산자
#loc[]: 명칭(label) 기반 데이터 추출
#행 위치에는 DataFrame index, 열 위치에는 columns 명 사용
data_df.loc['one','Name'] #'one'행 'Name'열 값인 데이터

'Chulmin'

In [133]:
#다음 코드는 오류를 발생
data_df.loc[0, 'Name']
#실제 인덱스값을 확인하고 입력하자

KeyError: 0

In [135]:
#loc[] 슬라이싱 유의점!!!
#일반적으로 슬라이싱을 'A:B' 같이 지정하면  A ~ B-1 까지의 범위를 의미한다
#그런데 loc[]에 슬라이싱을 지정하면 A ~ B까지의 범위를 포함한다
#이는 명칭 기반 인덱싱인 loc의 특성상 -1을 할 수 없기에 일어나는 현상이므로 주의한다
print('위치기반 iloc slicing\n', data_df.iloc[0:1, 0], '\n') #1번째 행(index 번호 0)만 출력
print('명칭기반 loc slicing\n', data_df.loc['one':'two', 'Name']) #one, two행 모두 출력

위치기반 iloc slicing
 one    Chulmin
Name: Name, dtype: object 

명칭기반 loc slicing
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object


In [141]:
#iloc와 다르게 loc는 불린 인덱싱이 가능하다
data_df.loc[data_df.Year >= 2014] #Year값이 2014이상인 데이터를 추출

Name  Year  Gender
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [142]:
#loc[], iloc[] 기억해야 할 점
#행과 열을 함께 사용하여 데이터를 추출해야 할 때 iloc[]나 loc[]를 사용
#iloc[]: 위치기반인덱싱, loc[]: 명칭기반인덱싱
#명칭기반인덱싱(loc[])에서 슬라이싱 범위 지정 시 종료점을 포함한 위치에 있는 데이터를 반환함

In [146]:
#불린 인덱싱
#[]와 loc[]에서 지원(iloc[]는 지원하지 않음)
titanic_df = pd.read_csv('titanic_train.csv')
titanic_boolean = titanic_df[titanic_df.Age > 60] #'Age'칼럼 값이 60 이상인 데이터를 반환한다
print(type(titanic_boolean)) #DataFrame 객체 타입을 가진다
titanic_boolean

<class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket  \
33            34         0       2  Wheadon, Mr...    male  66.0      0      0   C.A. 24579   
54            55         0       1  Ostby, Mr. ...    male  65.0      0      1       113509   
96            97         0       1  Goldschmidt...    male  71.0      0      0     PC 17754   
116          117         0       3  Connors, Mr...    male  70.5      0      0       370369   
170          171         0       1  Van der hoe...    male  61.0      0      0       111240   
252          253         0       1  Stead, Mr. ...    male  62.0      0      0       113514   
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   
280          281         0       3  Duane, Mr. ...    male  65.0      0      0       336439   
326          327         0       3  Nysveen, Mr...    male  61.0      0      0       345364   
438          439         0       1  Fortune, Mr...    male  64.0      1      4        19950   
456          457         0       1  Millet, Mr....    male  65.0      0      0        13509   
483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134   
493          494         0       1  Artagaveyti...    male  71.0      0      0     PC 17609   
545          546         0       1  Nicholson, ...    male  64.0      0      0          693   
555          556         0       1  Wright, Mr....    male  62.0      0      0       113807   
570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752   
625          626         0       1  Sutton, Mr....    male  61.0      0      0        36963   
630          631         1       1  Barkworth, ...    male  80.0      0      0        27042   
672          673         0       2  Mitchell, M...    male  70.0      0      0   C.A. 24580   
745          746         0       1  Crosby, Cap...    male  70.0      1      1    WE/P 5735   
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   
851          852         0       3  Svensson, M...    male  74.0      0      0       347060   

         Fare        Cabin Embarked  
33    10.5000          NaN        S  
54    61.9792          B30        C  
96    34.6542           A5        C  
116    7.7500          NaN        Q  
170   33.5000          B19        S  
252   26.5500          C87        S  
275   77.9583           D7        S  
280    7.7500          NaN        Q  
326    6.2375          NaN        S  
438  263.0000  C23 C25 C27        S  
456   26.5500          E38        S  
483    9.5875          NaN        S  
493   49.5042          NaN        C  
545   26.0000          NaN        S  
555   26.5500          NaN        S  
570   10.5000          NaN        S  
625   32.3208          D50        S  
630   30.0000          A23        S  
672   10.5000          NaN        S  
745   71.0000          B22        S  
829   80.0000          B28      NaN  
851    7.7750          NaN        S

In [148]:
#60세 이상인 승객의 이름과 나이 추출(3개만)
titanic_df[titanic_df.Age >= 60][['Name','Age']].head(3)

Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [152]:
#loc[]의 경우도 동일하게 적용 가능
#단 ['Name','Age']는 열 위치에 놓여야 한다
#이 경우 불린 조건이 행을 선택하고 ['Name','Age']가 열을 선택
titanic_df.loc[titanic_df.Age >= 60, ['Name','Age']].head(3)

Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [156]:
#여러 개의 복합 조건도 가능
#&: and 조건
#|: or 조건
#~: not 조건
titanic_df[ (titanic_df.Age >= 60) & (titanic_df.Pclass == 1) & (titanic_df.Sex == 'female') ]
#60세 이상이고 Pclass가 1이며 성별이 female인 데이터 반환

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare  \
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583   
366          367         1       1  Warren, Mrs...  female  60.0      1      0  110813  75.2500   
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   

    Cabin Embarked  
275    D7        S  
366   D37        C  
829   B28      NaN

In [158]:
#개별 조건을 변수에 할당하고 이를 결합해 불린 인덱싱 수행 가능
cond1 = titanic_df.Age >= 60
cond2 = titanic_df.Pclass == 1
cond3 = titanic_df.Sex == 'female'
titanic_df[ cond1 & cond2 & cond3 ]
#조건을 바로 []에 넣은 것과 같은 결과를 출력한다

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare  \
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583   
366          367         1       1  Warren, Mrs...  female  60.0      1      0  110813  75.2500   
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   

    Cabin Embarked  
275    D7        S  
366   D37        C  
829   B28      NaN

In [160]:
#sort_values(): 정렬
#주요 파라미터: by, ascending, inplace
#by: 특정 칼럼 입력 시 해당 칼럼으로 정렬 수행
#ascending: True이면 오름차순, False이면 내림차순, 기본값: True
#inplace: True이면 정렬 결과를 그대로 적용, False이면 정렬된 데이터프레임을 결과로 반환, 기본값: False

titanic_sorted = titanic_df.sort_values(by=['Name']) #이름순 오름차순 정렬
titanic_sorted.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare  \
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   

    Cabin Embarked  
845   NaN        S  
746   NaN        S  
279   NaN        S

In [162]:
#여러개의 칼럼으로 정리하려면 by에 리스트 형식으로 정렬하려는 칼럼을 전달
titanic_sorted = titanic_df.sort_values(by = ['Pclass','Name'], ascending=False)
#'Pclass','Name'을 기준으로 내림차순 정렬
titanic_sorted.head(3)

PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch    Ticket  Fare  \
868          869         0       3  van Melkebe...  male   NaN      0      0    345777   9.5   
153          154         0       3  van Billiar...  male  40.5      0      2  A/5. 851  14.5   
282          283         0       3  de Pelsmaek...  male  16.0      0      0    345778   9.5   

    Cabin Embarked  
868   NaN        S  
153   NaN        S  
282   NaN        S

In [165]:
#aggregation함수 (min, max, sum, count ..)
#aggregation함수를 호출할 경우 DataFrame의 모든 칼럼에 해당 aggregation함수 적용
#단 count()는 Null값을 반영하지 않은 결과를 반환
titanic_df.count()
#'Age','Cabin','Embarked'칼럼은 Null값이 존재하므로 결과가 다르다

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [166]:
#특정 칼럼에 aggregation함수를 적용하기 위해서 대상 칼럼들만 추출해 aggregation함수 적용
titanic_df[['Age','Fare']].mean()
#'Age','Fare' 칼럼에 mean()함수를 적용한다

Age     29.699118
Fare    32.204208
dtype: float64

In [167]:
#groupby()
#파라미터 by에 칼럼을 입력하면 대상 칼럼으로 groupby
titanic_groupby = titanic_df.groupby(by='Pclass') #Pclass칼럼 기준으로 그룹바이
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [169]:
#groupby()를 통해 호출된 결과에 aggregation함수를 호출하면 
#groupby()대상 칼럼을 제외한 모든 칼럼에 해당 함수 적용
titanic_groupby = titanic_df.groupby('Pclass').count()
#Pclass 칼럼을 제외한 모든 칼럼에 count()함수가 적용된 것을 볼 수 있다
titanic_groupby

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass                                                                                    
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [221]:
#DataFrame의 groupby()에 특정 칼럼만 agg함수를 적용하려면
#DataFrameGroupBy객체에 해당 칼럼을 필터링한 뒤 agg함수 적용
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()
#Pclass를 기준으로 groupby한 groupby객체에 PassengerId와 Survived를 필터링해 count()함수를 수행 
titanic_groupby

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [175]:
#여러개의 agg함수를 적용하려면 함수명을 agg()내에 인자로 입력해서 사용
titanic_df.groupby('Pclass')['Age'].agg([max,min])

C:\Users\motor\AppData\Local\Temp\ipykernel_16204\3412685520.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max,min])
C:\Users\motor\AppData\Local\Temp\ipykernel_16204\3412685520.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max,min])


max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [178]:
#여러개의 칼럼이 각각 다른 agg함수를 호출하려면?
#agg()내에 딕셔너리 형태로 함수가 적용될 칼럼과 함수를 입력한다
agg_format = {'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
#Age에는 max(), SibSp에는 sum(), Fare에는 mean() 함수를 적용한다
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

In [181]:
#결손 데이터 처리
#결손 데이터란 칼럼에 값이 없는 즉 Null인 경우를 의미하며 넘파이의 NaN으로 표시한다
#isna(): 결손 데이터 여부 확인
titanic_df.isna().head(3)
#모든 칼럼의 값이 NaN인지 여부를 알려준다

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  \
0        False     False   False  False  False  False  False  False   False  False   True   
1        False     False   False  False  False  False  False  False   False  False  False   
2        False     False   False  False  False  False  False  False   False  False   True   

   Embarked  
0     False  
1     False  
2     False

In [185]:
#isna()결과에 sum() 함수를 호출해 결손 데이터의 개수를 구할 수 있다
titanic_df.isna().sum()
#Age에는 177개, Cabin에는 687개, Embarked에는 2개의 결손데이터가 존재한다

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [201]:
#fillna(): 결손 데이터 대체
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
#Cabin칼럼의 NaN값을 C000으로 대체한다
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket  \
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599   
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   

      Fare Cabin Embarked  
0   7.2500  C000        S  
1  71.2833   C85        C  
2   7.9250  C000        S

In [203]:
#fillna()를 이용해 반환 값을 다시 받거나 inplace=True로 지정해야 실제 데이터 셋 값이 변경됨
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
#Age칼럼의 NaN값을 모두 Age의 평균값으로 대체
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
#Embarked칼럼의 NaN값을 모두 S로 대체
titanic_df.isna().sum()
#모든 NaN값을 대체함

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [204]:
#apply lambda 식으로 데이터 가공
#lambda식
def get_square(a):
    return a**2

print('3의 제곱은:', get_square(3))

3의 제곱은: 9


In [206]:
#lambda식은 위와 같은 함수의 선언과 함수 처리를 한 줄의 식으로 쉽게 변환한다
lambda_square = lambda x : x**2
#:로 입력 인자와 반환될 입력 인자의 계산식을 분리
#: 왼쪽에 있는 x는 입력 인자, 오른쪽은 입력 인자의 계산식
#오른쪽의 계산식은 결국 반환 값을 의미한다
print('3의 제곱은:', lambda_square(3))
#x에 3을 입력했고 계산식이 x**2이므로 3**2인 9를 반환한다

3의 제곱은: 9


In [209]:
#lambda식을 이용해 여러 개의 값을 입력 인자로 사용할 때는 map()함수를 결합해 사용
a = [1,2,3]
squares = map(lambda x: x**2, a)
list(squares)

[1, 4, 9]

In [212]:
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x : len(x))
#'Name_len'칼럼을 만들고 'Name'칼럼에 apply lambda를 이용해 len()함수를 적용한 값을 'Name_len' 칼럼에 입력한다
titanic_df[['Name','Name_len']].head(3)

Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

In [214]:
#apply lambda에 if else절 사용
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <= 15 else 'Adult')
#if 절의 경우 if식보다 반환 값을 먼저 기술해야 한다
#lambda x : 'Child'(반환값) if 조건 else 'Adult'(반환값)
#else 절의 경우 else식이 먼저 나온다
#else if는 지원하지 않음
titanic_df[['Age','Child_Adult']].head(3)

Age Child_Adult
0  22.0       Adult
1  38.0       Adult
2  26.0       Adult

In [219]:
#else if를 사용하려면 else 절을 ()로 내포해 다시 if else를 적용해야함
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x <= 15 
                                                else ('Adult' if x <= 60 else 'Elderly'))
#두번째 if문을 () 안에 내포해 else if를 구현함
titanic_df['Age_cat'].value_counts()

Age_cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

In [220]:
#그러나 else if가 많이 나와야 하는 경우나 switch case의 경우에 부담이 있을 수 있음
#이 경우 별도의 함수를 만들어 해결한다

#나이에 따라 세분화된 분류를 수행하는 함수 생성
def get_category(age):
    cat = ''
    if age <= 5: cat = 'Baby'
    elif age <= 12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age <= 25: cat = 'Student'
    elif age <= 35: cat = 'Young Adult'
    elif age <= 60: cat = 'Adult'
    else: cat = 'Eldery'

    return cat

#lambda식에 위에서 생성한 get_category()함수를 반환값으로 지정
#get_category(x)는 입력값으로 'Age' 칼럼 값을 받아서 해당하는 cat 반환
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x: get_category(x))
titanic_df[['Age','Age_cat']].head(3)

Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult