## 03 Numpy

In [1]:
import numpy as np

#### Numpy 기반 데이터 타입 ndarray
- array() : 입력 > ndarray
- ndarray.shape : 크기 (행, 열) & 차원
- ndarray.ndim : 차원

In [2]:
array1 = np.array([1,2,3])

In [3]:
print('array1 type:', type(array1))

array1 type: <class 'numpy.ndarray'>


In [5]:
print('array1 array 형태:', array1.shape)

array1 array 형태: (3,)


In [6]:
array2 = np.array([[1,2,3], 
                   [2,3,4]])

In [7]:
print('array2 type:', type(array2))

array2 type: <class 'numpy.ndarray'>


In [8]:
print('array2 array 형태', array2.shape)

array2 array 형태 (2, 3)


In [9]:
array3 = np.array([[1,2,3]])

In [10]:
print('array3 type:', type(array3))

array3 type: <class 'numpy.ndarray'>


In [11]:
print('array3 array 형태', array3.shape)

array3 array 형태 (1, 3)


In [12]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


In [ ]:
# array1과 array3은 동일한 데이터 건수를 가지고 있지만, 차원이 다르다.
# 이로 인해 생기는 오류를 해결하려면, 차원의 차수를 변경해야 한다. > reshape()

### ndarray 내의 데이터 타입은 연산 특성상 같은 데이터 타입만 가능하다
- ndarray.dtype : ndarray 내 데이터 타입 확인
- 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 > 데이터 크기가 더 큰 타입으로 일관 형 변환
- ndarray.astype() : ndarray 내 데이터값의 타입 변경 (메모리 절약해야 할 때)

In [15]:
list1 = [1,2,3]
print(type(list1))

<class 'list'>


In [16]:
array1 = np.array(list1)
print(type(array1))

<class 'numpy.ndarray'>


In [17]:
print(array1, array1.dtype)

[1 2 3] int32


In [18]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [19]:
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


In [20]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [21]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [22]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


### ndarray 편리하게 생성
- arange() : range()와 유사
- zeros() : 튜플 형태의 shape 입력 > 모두 0으로 채운 ndarray 반환 
- ones() : 튜플 형태의 shape 입력 > 모두 1로 채운 ndarray 반환

In [25]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [26]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [27]:
one_array = np.ones((3,2)) # 디폴트 'float64'
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()
- ndarray.reshape()
- 지정된 사이즈로 변경 불가하면 오류
- -1을 인자로 사용하면?

In [30]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [31]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [32]:
array1 = np.arange(10)
print(array1)

# -1을 인자
array2 = array1.reshape(-1,5) # 고정된 5개 컬럼에 맞는 로우를 자동으로 생성해 변환
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [33]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) # 변경 불가하면 오류

ValueError: cannot reshape array of size 10 into shape (4)

In [34]:
## reshape(-1,1) : 원본 ndarray의 형태와 관계 없이, 2차원 + 반드시 1개의 컬럼을 가진 ndarray로 변환
# 여러 ndarray의 형태를 통일할 때 유용
# ndarray.tolist() : ndarray > list

In [35]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [36]:
# 3차원 ndarray를 2차원 ndarray로
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [37]:
# 1차원 ndarray를 2차원 ndarray로
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 인덱싱 (Indexing)
- 특정 데이터만 추출
- 슬라이싱 (Slicing)
- 팬시 인덱싱 (Fancy Indexing)
- 불린 인덱싱 (Boolean Indexing)

#### 특정 데이터만 추출

In [40]:
# 단일 인덱스
array1 = np.arange(1, 10)
print('array1:', array1)

# index는 0부터 시작 > array1[2] : 3번째 index 위치의 데이터값
value = array1[2]
print('value:', value)
print(type(value))

print('맨 뒤의 값:', array1[-1], ' 맨 뒤에서 두 번째 값:', array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤의 값: 9  맨 뒤에서 두 번째 값: 8


In [41]:
# 단일 인덱스로 ndarray 내의 데이터값 수정
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [42]:
# 2차원 ndarray에서 특정 데이터 추출 : [row, col] = [axis0, axis1]
# 축 기반의 연산에서 axis가 생략 > axis 0 의미
array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


#### 슬라이싱
- ndarray 반환
- array2d[:2, 0] : 한 축에는 슬라이싱 + 다른 축에는 단일 값 인덱스

In [44]:
array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [45]:
array1 = np.arange(1,10)
array4 = array1[:3]
print(array4)

[1 2 3]


In [46]:
array5 = array1[3:]
print(array5)

[4 5 6 7 8 9]


In [47]:
array6 = array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]


In [48]:
# 2차원 ndarray에서의 슬라이싱
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [51]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


#### 팬시 인덱싱
- 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환

In [52]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

In [54]:
array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ', array3.tolist())

array2d[[0,1], 2] =>  [3, 6]


In [55]:
array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ', array4.tolist())

array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]


In [56]:
array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


#### 불린 인덱싱 : 조건 필터링과 검색을 동시에

In [58]:
array1d = np.arange(1,10)
print(array1d > 5)
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

[False False False False False  True  True  True  True]
array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [60]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [61]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬
- sort()
    - np.sort() : 원 행렬 유지 & 정렬된 행렬 반환
    - ndarray.sort() : 원 행렬 정렬 & None 반환
- argsort() : 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환

In [ ]:
# sort()

In [62]:
org_array = np.array([3,1,9,5])
print('원본 행렬: ', org_array)

# np.sort()
sort_array1 = np.sort(org_array)
print('np.sort() 후 반환된 정렬 행렬: ', sort_array1)
print('np.sort() 후 원본 행렬: ', org_array)

# ndarray.sort()
sort_array2 = org_array.sort()
print('org_array.sort() 후 반환된 행렬: ', sort_array2)
print('org_array.sort() 후 원본 행렬: ', org_array)

원본 행렬:  [3 1 9 5]
np.sort() 후 반환된 정렬 행렬:  [1 3 5 9]
np.sort() 후 원본 행렬:  [3 1 9 5]
org_array.sort() 후 반환된 행렬:  None
org_array.sort() 후 원본 행렬:  [1 3 5 9]


In [63]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬: ', sort_array1_desc)

내림차순으로 정렬:  [9 5 3 1]


In [64]:
# 2차원 행렬 정렬
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬: \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬: \n', sort_array2d_axis1)

로우 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬: 
 [[ 8 12]
 [ 1  7]]


In [ ]:
# argsort()

In [65]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스: ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스:  [1 0 3 2]


In [66]:
# 내림차순 정렬의 경우
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스: ', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스:  [2 3 0 1]


In [69]:
# argsort()의 활용
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 socre_array 인덱스: ', sort_indices_asc)
print('성적 오름차순으로 name_array 이름 출력: ', name_array[sort_indices_asc])

성적 오름차순 정렬 시 socre_array 인덱스:  [0 2 4 1 3]
성적 오름차순으로 name_array 이름 출력:  ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 행렬 내적과 전치 행렬
- np.dot() : 행렬 내적
- np.transpose() : 전치 행렬

In [ ]:
# np.dot()

In [70]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
doc_product = np.dot(A,B)
print('행렬 내적 결과:\n', doc_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [71]:
# np.transpose()

In [72]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
