# 1. 파이썬 기반의 머신러닝과 생태계 이해

## 1-1. NumPy

### ndarray 개요

In [11]:
import numpy as np

In [12]:
array1 = np.array([1,2,3])    # array() 함수는 리스트처럼 다양한 인자를 입력받아 ndarray로 변환. 이 경우, 1차원 array
print('array1 type: ', type(array1))
print('array1 type 형태: ', array1.shape)    # shape는 ndarray의 크기 - 행과 열의 수, 차원을 튜플로 나타냄

array2 = np.array([[1,2,3], [2,3,4]])    # 2차원 array (2x3)
print('array1 type: ', type(array2))
print('array1 type 형태: ', array2.shape)

array3 = np.array([[1,2,3]])    # 2차원 array (1x3), array1과 다름을 인지.
print('array1 type: ', type(array3))
print('array1 type 형태: ', array3.shape)

array1 type:  <class 'numpy.ndarray'>
array1 type 형태:  (3,)
array1 type:  <class 'numpy.ndarray'>
array1 type 형태:  (2, 3)
array1 type:  <class 'numpy.ndarray'>
array1 type 형태:  (1, 3)


In [13]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))    # 각 array 차원 확인

array1: 1차원, array2: 2차원, array3: 2차원


### ndarray의 데이터 타입

In [14]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)    # 데이터 타입 확인 -> dtype

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [15]:
list2 = [1, 2, 'test']
array2 = np.array(list2)    # ndarray 내에는 같은 데이터 타입만 가능. 여러 유형이 섞인 리스트를 ndarray로 변경시 데이터 크기가 더 큰 데이터 타입으로 형 변환
print(array2, array2.dtype)    # int형이 유니코드 문자열 값으로 변환

list3 = [1, 2, 3.0]    # int형이 float64형으로 변환
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [16]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')    # ndarray 내 데이터 타입 변경 -> astype(). 이 경우, int32형 데이터를 float64로 변환
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')    # float64를 int32로 변환
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')    # float64를 int32로 변환
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [17]:
sequence_array = np.arange(10)    # arange()는 range()와 유사한 기능. 일정 범위의 연속된 정수 생성(0부터 함수인자 값 -1 까지)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [18]:
zero_array = np.zeros((3,2), dtype='int32')    # zeros는 함수인자로 튜플 형태의 shape 입력시 해당 shape의 0으로 초기화된 ndarray 반환
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))    # ones는 1로 초기화된 ndarray 반환. dtype을 정해주지 않으면 default로 float64형
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()

In [19]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)    # reshape()는 ndarray를 특정 차원 및 크기로 변환
print('array2:\n', array2)

array3 = array2.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
array1.reshape(4,3)    # 지정된 사이즈로 변경이 불가능하면 오류

ValueError: cannot reshape array of size 10 into shape (4,3)

In [21]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)    # -1을 인자로 사용시 원래 ndarray와 호환되는 새로운 shape(고정된 로우 또는 칼럼에 맞게)로 변환 
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [22]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [23]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())    # tolist()는 ndarray를 리스트 자료형으로 변환

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

In [24]:
# 1부터 9가지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미(단일 값 추출)
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [25]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8


In [26]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)    # 단일 인덱스로 ndarray 내의 데이터값을 간단히 수정가능

array1: [9 2 3 4 5 6 7 8 0]


In [27]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

# 2차원 ndarray에서 단일 값 추출 - [row, col]을 이용
print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [28]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]    # 시작 인덱스와 종료 인덱스 사이에 : 기호를 이용해 연속한 데이터를 슬라이싱하여 추출가능. 
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [29]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]    # 시작 인덱스 생략시 처음을 0으로 간주
print(array4)

array5 = array1[3:]    # 종료 인덱스 생략시 마지막 인덱스로 간주
print(array5)

array6 = array1[:]    # 시작/종료 인덱스 생략이 처음/마지막 인덱스로 간주
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [30]:
array1 = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

# 2차원 ndarray 슬라이싱도 1차원과 유사하며 ,로 로우와 칼럼을 지칭하는 부분 추가
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [31]:
print(array2d[0])    # 2차원 ndarray 뒤에 오는 인덱스를 없애면 첫 번째 로우 ndarray 반환(==1차원 ndarray)
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape (3,)


In [32]:
array1 = np.arange(start=1, stop=10)
array2 = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]     # 리스트나 ndarray로 지정한 인덱스 집합에 해당하는 ndarray 반환(Fancy Indexing)
print('array2d[[0,1], 2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


In [33]:
array1d = np.arange(start=1, stop=10)
# [ ]안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [34]:
array1d > 5    # ndarray 객체에 조건식 할당 시 True, False 값 반환(Boolean Indexing 동작 단계1)

array([False, False, False, False, False,  True,  True,  True,  True])

In [35]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]    # 해당 조건으로 반환된 ndarray 객체를 []내에 입력하면 False값은 무시하고 True 값이 있는 위치 인덱스만 저장(Boolean Indexing 동작 단계2)
print('불린 인덱스로 필터링 결과 :', array3)    # 저장된 인덱스 값으로 데이터 조회(Boolean Indexing 동작 단계3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [36]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)    #직접 인덱스 집합을 만들어 대입한 결과와 동일

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()

In [37]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)
# np.sort()로 정렬 - 원 행렬은 그대로 유지한 채 정렬된 행렬을 반환(오름차순 정렬)
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
# ndarray.sort()로 정렬 - 원 행렬 자체를 정렬한 형태로 변환하며 반환값은 None
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [38]:
sort_array1_desc = np.sort(org_array)[::-1]    # 내림차순으로 정렬
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [39]:
array2d = np.array([[8, 12],
                   [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)    # 2차원 이상의 행렬은 axis 축 값 설정을 통해 로우 방향, 칼럼 방향으로 정렬
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [40]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)    # np.argsort()는 (오름차순)정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [41]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]    # 내림차순으로 정렬 시 원본 행렬의 인덱스 반환
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [42]:
# argsort() 메타 데이터 활용

import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [43]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])
dot_product = np.dot(A, B)    # 행렬 내적
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [44]:
A = np.array([[1,2],
             [3,4]])
transpose_mat = np.transpose(A)    # 전치 행렬
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
