# 넘파이
# Numpy ndarray 개요

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [5]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [6]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


ndarray를 편리하게 생성하기 - arange, zeros, ones

In [7]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [8]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


reshape

In [9]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array1.reshape(4,3) #사이즈 배수가 아니라서 reshape못함

ValueError: cannot reshape array of size 10 into shape (4,3)

In [12]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)   #-1의 의미는 적절한 사이즈로 reshape 하라는 뜻인듯
print(array2)
print('array2 shape:',array2.shape)

print(array3)
array3 = array1.reshape(5,-1)  #위와 마찬가지
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
array2 shape: (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3 shape: (5, 2)


In [13]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)  #적절한 배수가 아니면 ValueError 뜸

ValueError: cannot reshape array of size 10 into shape (4)

In [14]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))    #3차원으로 reshape
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)   #2차원이면서 원소개수가 1인
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


**indexing**

- 단일값 추출

In [16]:
# 1에서 부터 9 까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [17]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [18]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [19]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


- Slicing

In [20]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [21]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]  #3까지 자르면 0부터 2까지 잘라져서 총 3개나옴
print(array4)

array5 = array1[3:]  #3부터하면 인덱스 3부터 시작 (1, 2, 3, [4, 5, 6, 7, 8, 9])
print(array5)

array6 = array1[:]  #전체의미
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [23]:
array1d = np.arange(start=1, stop=10)   #행렬 인덱싱
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)
print('---------------------')
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('---------------------')
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('---------------------')
print('array2d[1:3, :] \n', array2d[1:3, :])
print('---------------------')
print('array2d[:, :] \n', array2d[:, :])
print('---------------------')
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('---------------------')
print('array2d[:2, 0] \n', array2d[:2, 0]) #얘는 1차원이 됐네

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------------
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
---------------------
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
---------------------
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
---------------------
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------------
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
---------------------
array2d[:2, 0] 
 [1 4]


In [24]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


- fancy indexing

In [27]:
array1d = np.arange(start=1, stop=10) #1부터 9까지 리스트 만들고
array2d = array1d.reshape(3,3)
print('array2d => ', array2d.tolist())


array3 = array2d[[0,1], 2]  #앞에 0행과 1행에서 2번째 인덱스 원소
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d =>  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


- Boolean indexing

In [28]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]   #이런것도 되네 편리하다
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [30]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [31]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [32]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]   #인덱스를 list로 담아서 인덱스로 넣어도 해당 인덱스의 원소로 필터링 가능
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


# 행렬의 정렬 – sort( )와 argsort( )

- 행렬 정렬

In [33]:
org_array = np.array([ 3, 1, 9, 5])
print('원본 행렬:', org_array)
# np.sort( )로 정렬
sort_array1 = np.sort(org_array)       #np.sort는 default가 오름차순으로 정렬하고 반환값으로 넘김  , 원본은 건들지 않음
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()         #ndarray.sort는 반환하는 값 없이 원본을 바로 바꿈  / 상황에 맞게 쓰기
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [34]:
sort_array1_desc = np.sort(org_array)[::-1]  #reverse를 이런식으로 사용
print ('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [35]:
array2d = np.array([[8, 12],
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)     #행끼리 비교하면 [8,12] 와 [7,1] 을 비교하는데 7이 8보다 작아서 행이 앞으로 오게되었음
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)     #열끼리 비교하면 첫번째 열은 [8,7] 이고 두번째 열은 [12,1]임 8은 12보다 작으므로 8, 12가 앞으로 오게됨
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)  #맞는지 물어보면 좋겠다

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


- 정렬 행렬의 인덱스 반환

In [37]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices = np.argsort(org_array)   #np.argsort는 정렬한 리스트의 인덱스 순서를 리스트로 반환해준다.(알고리즘 할 때도 써먹을 수 있을듯)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [38]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]   #이번엔 원소가 큰 순서대로 인덱스를 반환
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [39]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)   #성적 낮은순서로 인덱스를 뽑기
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc]) #그대로 name_array의 인덱스로 활용해서 순서대로 뽑기 (내부적으로 iterate하는듯)

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

- 행렬 내적

In [40]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)  # (2x3)이랑 (3x2) 했으니까 (2x2) 행렬로 나와야함  np.dot이 내적
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


- 전치 행렬

In [41]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)     # A^T 구하기
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
