# 01. 파이썬 기반의 머신러닝과 생태계 이해

## 1. 넘파이

- Numerical Python을 의미한다.
- 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지
- 대량 데이터의 배열 연산 가능
- 다양한 데이터 핸들링 기능 제공

### 1-1. 넘파이 ndarray 개요

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3]) # array() 함수는 파이썬의 리스트와 같은 인자를 입력받아 ndarray로 변환하는 기능 수행
print('array1 type:', type(array1))  # 여기서 ndarray는 넘파의 기반 데이터 타입으로 다차원 배열을 쉽게 생성 및 연산 수행
print('array1 array 형태:', array1.shape)  # shape는 ndarray의 차원과 크기를 튜플 형태로 나타냄

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])  # 1개의 로우와 3개의 칼럼으로 구성된 2차원 데이터
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)  # 데이터값으로는 동일하나 차원이 달라서 오류가 발생하는 경우 조심

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))
#  리스트 []는 1차원, 리스트의 리스트 [[]]는 2차원

array1: 1차원, array2: 2차원, array3: 2차원


### 1-2. ndarray의 데이터 타입

- ndarray 내의 데이터 값은 숫자, 문자열, 불 모두 가능하다.
- 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다. (한 개의 ndarray 객체에 int와 float 불가능)

In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)  # dtype 속성으로 ndarray 내의 데이터 타입 확인 가능

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


- 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용한다.

In [5]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)  # 1과 2 모두 문자열 값으로 변환

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)  # 1과 2가 모두 float64형으로 변환

['1' '2' 'test'] <U11
[1. 2. 3.] float64


- astype() 메서드를 통해 ndarray 내 데이터값의 타입을 변경한다.

In [6]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')  # int형을 float64형으로 타입 변경
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')  # 다시 int32형으로 타입 변경
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])  # 소수이므로 float형이지만, astype() 메서드를 통해 int형으로 타입 변경
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)  # 소수점 이하는 모두 사라짐

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### 1-3. ndarray를 편리하게 생성하기 - arange, zeros, ones

- ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우 발생

In [7]:
sequence_array = np.arange(10)  # 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [8]:
zero_array = np.zeros((3,2), dtype='int32')  # 함수 인자로 dtype을 정해주지 않으면 default로 float64 형의 데이토로 채움
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### 1-4. ndarray의 차원과 크기를 변경하는 reshape()

- 특정 차원 및 크기로 변환
- 변환을 원하는 크기를 함수 인자로 부여

In [9]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)  # 2로우x5칼럼으로 변환
print('array2:\n', array2)

array3 = array1.reshape(5,2)  # 5로우x2칼럼으로 변환
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array1.reshpae(4,3)  # 지정된 사이즈로 변경이 불가능하면 오류 발생

AttributeError: 'numpy.ndarray' object has no attribute 'reshpae'

In [11]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)  # 고정된 5개의 칼럼에 맞는 로우를 자동으로 생성
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)  # 고정된 5개의 로우에 맞는 칼럼을 자동으로 생성
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [12]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)  # 고정된 4개의 칼럼을 가진 로우로는 변경 불가능

ValueError: cannot reshape array of size 10 into shape (4)

- -1 인자는 reshape(-1,1)와 같은 형태로 자주 사용됨
- 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨
- stack이나 concat으로 결합할 때 각각의 ndarray로 변환됨을 보장함

In [13]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())  # tolist() 메서드를 통해 ndarray를 리스트 자료형으로 변환

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 1-5. 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

1) 특정한 데이터만 추출
2) 슬라이싱
3) 팬시 인덱싱
4) 불린 인덱싱

**단일 값 추출**

In [14]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)  # 시작값의 default는 0이므로 1로 설정
print('array1:', array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))  # ndarray 타입이 아닌 ndarray 내의 데이터값을 의미

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [15]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [16]:
array1[0] = 9  # 인덱스를 지정해서 데이터값 수정 가능
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [17]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)  # 2차원의 3x3 ndarray로 변환
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])  # 콤마(,)로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


cf) 넘파이 ndarray에서는 로우와 칼럼을 사용하지 않는다.
-> axis 0, axis 1이 정확한 표현이다.

**슬라이싱**

In [18]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]  # : 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1의 위치에 있는 ndarray 반환
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


1) : 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
2) : 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주
3) : 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

In [19]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]  # 시작 인덱스 0으로 간주
print(array4)

array5 = array1[3:]  # 종료 인덱스 마지막으로 간주
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [20]:
array1d = np.arange(start=1, stop=10)  # 2차원 ndarray에서 슬라이싱으로 데이터에 접근
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])  # 첫 번째는 axis 0의 개수를 정하고, 두 번째는 axis 1의 개수를 정한다.
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:,:] \n', array2d[:,:])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('arrray2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
arrray2d[:2, 0] 
 [1 4]


In [21]:
print(array2d[0])  # axis 0의 첫 번째 로우 ndarray를 변환
print(array2d[1])  # 반환되는 ndarray는 1차원
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


**팬시 인덱싱**

- 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [22]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]  # 로우 축에 팬시 인덱싱 적용, 칼럼 축에 단일 값 인덱싱 적용
print('array2d[[0,1],2] =>', array3.tolist())  # (0,2), (1,2) 적용

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())  # ((0,0),(0,1)), ((1,0), (1,1)) 적용

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())  # ((0,:), (1,:)) 적용

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


**불린 인덱싱**

- 조건 필터링과 검색을 동시에 할 수 있음

In [23]:
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [24]:
array1d > 5  #  넘파이 ndarray 객채에 조건식 할당
# ndarray 객체에 조건식만 붙였을 뿐인데 False, True로 이뤄진 ndarray 객체가 변환

array([False, False, False, False, False,  True,  True,  True,  True])

In [26]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [27]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


Step 1 : array1d > 5와 같이 ndarray의 필터링 조건을 [] 안에 기재  
Step 2 : False 값은 무시하고 True 값에 해당하는 인덱스값만 저장  
(유의해야 할 사항은 True값 자체인 1을 저장하는 것이 아니라 **True값을 가진 인덱스를 저장한다는 것**)  
Step 3 : 저장된 인덱스 데이터 세트로 ndarray 조회  

### 1-6. 행렬의 정렬 - sort()와 argsort()

**행렬 정렬**

In [28]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)
# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)  # 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬 반환
print('np.sort() 호출 후 원본 행렬:', org_array)
# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)  # 원 행렬 자체를 정렬한 형태로 변환, 반환값은 0
print('org_array.sort() 호출 후 원본 행렬:', org_array)  # 정렬한 형태를 새로운 변수에 저장할 필요가 없음

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [29]:
sort_array1_desc = np.sort(org_array)[::-1]  # 내림차순은 슬라이싱 활용
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [30]:
array2d = np.array([[8,12],
                   [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


**정렬된 행렬의 인덱스를 반환하기**

- 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort() 이용

In [31]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))  # 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [32]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]  # 내림차순은 슬라이싱 활용
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


- 시험 성적순으로 학생 이름을 출력하고자 한다면 np.argsort(score_array)를 이용해 반환된 인덱스를 name_array에 팬시 인덱스로 적용

In [33]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 1-7. 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

**행렬 내적(행렬 곱)**

In [34]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])
dot_product = np.dot(A,B)  # np.dot()을 이용해 두 행렬의 내적을 계산 가능
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


**전치 행렬**

In [35]:
A = np.array([[1,2],
             [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
