## 넘파이 ndarray 개요

In [86]:
#넘파이 모듈 임포트
import numpy as np

In [87]:
#1차원 리스트 타입, 형태
array1 = np.array([1,2,3])
print ('array1 type:', type(array1))
print ('array1 array 형태:', array1.shape)

#2x3 리스트 타입, 형태
array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print ('array2 array 형태:', array2.shape)

#1x3 리스트 타입, 형태
array3 = np.array([[1,2,3]])
print ('array3 type:', type(array3))
print ('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [88]:
#ndim 함수를 통한 ndarray 차원 확인
print('array1: {0}차원, array2: {1}차원, array: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array: 2차원


## ndarray의 데이터 타입

In [89]:
# 리스트의 타입 확인
list1 = [1, 2, 3]
print(type(list1))

# ndarray의 타입 확인
array1 = np.array(list1)
print(type(array1))

# ndarray 출력과 속성의 데이터 타입 확인
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [90]:
# int형 값이 있는 리스트에 문자열이 들어간 list -> ndarray 변환 후 type, dtype 확인
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(type(array2))
print(array2, array2.dtype)

# int형 값이 있는 리스트에 float형 값이 들어간 list -> ndarray 변환 후 type, dtype 확인
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(type(array3))
print(array3, array3.dtype)

<class 'numpy.ndarray'>
['1' '2' 'test'] <U11
<class 'numpy.ndarray'>
[1. 2. 3.] float64


In [91]:
#int형 값이 있는 ndarray를 astype 메서드를 통해 float형으로 일괄변경
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

#float형 값이 있는 ndarray를 astype 메서드를 통해 int형으로 일괄변경
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

#float형 값이 있는 ndarray를 astype 메서드를 통해 int형으로 일괄변경
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## ndarray를 편리하게 생성하기 - arange, zeros, ones

In [92]:
#arange 함수를 이용하여 ndarray 생성하기
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [93]:
# zeros 함수를 이용하여 3X2 크기의 ndarray 생성하기
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# ones 함수를 이용하여 3X2 크기의 ndarray 생성하기
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 차원과 크기를 변경하는 reshape()

In [94]:
#1x10 크기의 ndarray 형성
array1 = np.arange(10)
print('array1:\n', array1)

#reshape 함수로 2x5 크기의 ndarray로 변경
array2 = array1.reshape(2,5)
print('array2:\n', array2)

#reshape 함수로 5x2 크기의 ndarray로 변경
array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [95]:
# 잘못된 크기로 reshape 할 경우
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [96]:
#1x10 크기의 ndarray 형성
array1 = np.arange(10)
print(array1)

#고정된 5열의 크기에 맞춰서 알맞은 행의 크기로 reshpae
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

#고정된 5행의 크기에 맞춰서 알맞은 행의 크기로 reshpae
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [97]:
#1x10 크기의 ndarray 형성
array1 = np.arange(10)
#고정된 4열의 크기에 맞춰서 알맞은 행의 크기로 reshpae
array = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [98]:
#1차원 ndarray를 3차원 ndarray로 변환
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print('array3d:\n',array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,2)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0, 1], [2, 3], [4, 5], [6, 7]]
array6 shape: (4, 2)


## 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

### 단일값 추출

In [99]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [100]:
#뒤에서 부터 인덱싱
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [101]:
#인덱스를 이용한 ndarray 값 수정
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [102]:
#2차원 ndarray 인덱싱
array1d = np.arange(start=1, stop=10)
#1차원 ndarray -> 3x3 크기의 2차원 ndarray 로 변환
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


### 슬라이싱

In [103]:
#ndarray 슬라이싱
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [104]:
#처음 값부터 3번째 값까지 슬라이싱
array1 = np.arange(start=1, stop=10)
array4 =array1[:3]
print(array4)
#4번째 값부터 끝 값까지 슬라이싱
array5 = array1[3:]
print(array5)
#모든 값 슬라이싱
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [105]:
#2차원 ndarray 슬라이싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

#열 0:2, 행 0:2 범위의 2차원 ndarray 슬라이싱
print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])

#열 1:3, 행 0:3 범위의 2차원 ndarray 슬라이싱
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])

#열 1:3, 행 전체 범위의 2차원 ndarray 슬라이싱
print('array2d[1:3, :]\n', array2d[1:3, :])

#열 전체, 행 전체 범위의 2차원 ndarray 슬라이싱
print('array2d[:, :]\n', array2d[:, :])

#열 :2, 행 1: 범위의 2차원 ndarray 슬라이싱
print('array2d[:2, 1:]\n', array2d[:2, 1:])

#열 :2, 첫 행 범위의 2차원 ndarray 슬라이싱
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [106]:
#2차원 ndarray 인덱싱에서 하나의 인덱스만 입력시 -> 입력한 인덱스의 행 반환
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### 팬시 인덱싱

In [107]:
#1x10 ndarray 형성 후 3x3 형태로 reshape
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

# 1~2행, 3열 인덱싱
array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

#1~2행, 0~1열 인덱싱
array4 = array2d[[0,1],0:2]
print('array2d[[0,1],2] =>', array4.tolist())

#0~1행, 전체 열 인덱싱
array5 = array2d[[0,1]]
print('array2d[[0,1],2] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],2] => [[1, 2], [4, 5]]
array2d[[0,1],2] => [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱

In [108]:
array1d = np.arange(start=1, stop=10)
#[] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :, array3')

array1d > 5 불린 인덱싱 결과 값 :, array3


In [109]:
#ndarray 객체에 조건식 할당했을 때
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [110]:
#불린 ndarray를 만들고 인덱스로 입력
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [111]:
#인덱스 집합을 만들어 대입
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


# 행렬의 정렬 - sort()와 argsort()

### 행렬 정렬

In [112]:
#넘파이에서 sort() 호출하여 ndarray 정렬
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

    #np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환 된 정렬 행렬:', sort_array1)
#ndarray.sort()로 정렬
print('np.sort() 호출 후 원본 행렬:', org_array)

    #ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환 된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [113]:
#내림차순 정렬
sort_array1_desc = np.sort(org_array)[::1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [1 3 5 9]


In [114]:
#2차원 행렬 정렬
array2d = np.array([[8, 12],[7, 1]])
    
# row 방향으로 정렬(axix=0)    
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

# columns 방향으로 정렬(axix=1)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스를 반환하기

In [115]:
#argsort() 를 이용하여 정렬된 원본 행렬 인덱스 추출
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [116]:
#행렬 내림차순 이후 원본 행렬 인덱스 추출
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬 인덱스: [2 3 0 1]


In [117]:
# argsort 로 메타데이터 정렬 하기(메타데이터 -> 별도의 ndarray => argsort 로 같이 정렬 가능)
import numpy as np

name_array = np.array(['John','Mike','Sarah','Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 선형대수 연산 - 행렬 내적 전치 행렬 구하기

### 행렬 내적(행렬 곱)

In [118]:
# 행렬 내적(행렬 곱 연산)
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### 전치행렬

In [119]:
#전치행렬 변환
A = np.array([[1,2], [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
