# 넘파이 ndarray 개요



In [1]:
import numpy as np # 넘파이 모듈 임포트

In [2]:
array1 = np.array([1, 2, 3]) # array() 함수는 인자를 입력받아 ndarray로 변환하는 기능을 수행
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) # 1차원 array, 3개의 데이터

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape) # 2차원 array, 2개의 로우와 3개의 칼럼

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape) # 2차원 array 1개의 로우와 3개의 칼럼

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim)) 

# ndim : array의 차원
# array 함수의 인자로는 파이썬의 리스트 객체가 주로 사용됨

array1: 1차원, array2: 2차원, array3: 2차원


# ndarray의 데이터 타입
- ndarray의 데이터 타입은 같은 데이터 타입만 가능
- 한 개의 ndarray 객체에 int와 float가 함께 있을 수 없음

In [4]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype) # ndarray 내의 데이터 타입은 dtype 속성으로 확인할 수 있음

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
# 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용

list2 = [1, 2, 'test']
array2 = np.array(list2) 
print(array2, array2.dtype) # 숫자형 값이 문자열 값으로 변환됨

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # int형이 float형으로 변환됨

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [6]:
# astype() 메서드를 통해 ndarray 내 데이터 값의 변경
# 메모리를 절약해야 할 때 보통 이용됨

array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64') # 원하는 타입을 문자열로 지정
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype) # float를 int형으로 변환할 때 소수점 이하는 사라짐

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray를 편리하게 생성하기 - arange, zeros, ones

### arange()
- array를 range()로 표현
- 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환

In [7]:
sequence_array = np.arange(10) # start 값도 부여할 수 있음
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


### zeros()
- 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환

### ones()
- 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환

In [8]:
zero_array = np.zeros((3, 2), dtype = 'int32') # dtype을 정해주지 않으면 default로 float64
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2)) # dtype을 정해주지 않으면 default로 float64
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# ndarray의 차원과 크기를 변경하는 reshape()

In [9]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array2.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
# 지정된 사이즈로 변환이 불가능하면 오류 발생
array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [11]:
# 인자로 -1을 적용하면 ndarray와 호환되는 새로운 shape로 변환

array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [12]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [13]:
array1 = np.arange(8)
array3d = array1.reshape(2, 2, 2)
print('array3d:\n', array3d.tolist()) # tolist() 메서드를 이용해 리스트 자료형으로 변환

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


# 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
- 특정한 데이터만 추출
- 슬라이싱(Slicing)
- 팬시 인덱싱(Fancy Indexing)
- 불린 인덱싱(Boolean Indexing)

In [14]:
# 단일 값 추출

# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(1, 10)
print('array1:', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [15]:
print('맨 뒤의 값 :', array1[-1], '맨 뒤에서 두번째 값 :', array1[-2])

맨 뒤의 값 : 9 맨 뒤에서 두번째 값 : 8


In [16]:
array1[0] = 9
array1[8] = 0
print('array1 :', array1)

array1 : [9 2 3 4 5 6 7 8 0]


In [17]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row = 0, col = 0) index 가리키는 값 : ', array2d[0, 0])
print('(row = 0, col = 1) index 가리키는 값 : ', array2d[0, 1])
print('(row = 1, col = 0) index 가리키는 값 : ', array2d[1, 0])
print('(row = 2, col = 2) index 가리키는 값 : ', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row = 0, col = 0) index 가리키는 값 :  1
(row = 0, col = 1) index 가리키는 값 :  2
(row = 1, col = 0) index 가리키는 값 :  4
(row = 2, col = 2) index 가리키는 값 :  9


In [18]:
# 슬라이싱

array1 = np.arange(1, 10)
array3 = array1[0:3]
print(array3)
print(type(array3)) # 추출된 데이터 세트는 ndarray 타입

[1 2 3]
<class 'numpy.ndarray'>


In [19]:
array1 = np.arange(1, 10)
array4 = array1[:3] # 시작 인덱스를 생략하면 0으로 간주
print(array4)

array5 = array1[3:] # 종료 인덱스를 생략하면 마지막 인덱스로 간주
print(array5)

array6 = array1[:] # 시작/종료 인덱스를 생략하면 맨 처음/맨 마지막 인덱스로 간주
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [20]:
array1d = np.arange(1, 10)
array2d = array1.reshape(3, 3)
print('array2d : \n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [21]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape :', array2d[0].shape, 'array2d[1] shape :', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape : (3,) array2d[1] shape : (3,)


In [22]:
# 팬시 인덱싱

array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2] # 리스트나 ndarray로 인덱스 집합을 지정
print('array2d[[0, 1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] =>', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


In [23]:
# 불린 인덱싱

array1d = np.arange(1, 10)
# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5] # 조건 필터링과 검색을 동시에
print('array1d > 5 Boolean indexing 결과 값 :', array3)

array1d > 5 Boolean indexing 결과 값 : [6 7 8 9]


In [24]:
array1d > 5  # False, True로 이루어진 ndarray 객체 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [25]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [26]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


# 행렬의 정렬 - sort() 와 argsort()

- np.sort() - 원 행렬은 그대로 유지한 채  원 행렬의 정렬된 행렬 반환
- ndarray.sort() 원 행렬 자체를 정렬한 형태로 변환, 반환 값은 None
- np.argsort()  정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [27]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬 :', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np_sort() 호출 후 반환된 정렬 행렬 :', sort_array1)
print('np_sort() 호출 후 원본 행렬 :', org_array) # 원본 행렬은 변하지 않음

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('ndarray_sort() 호출 후 반환된 행렬 :', sort_array2)
print('ndarray_sort() 호출 후 원본 행렬 :', org_array) # 원본 행렬 변환됨

원본 행렬 : [3 1 9 5]
np_sort() 호출 후 반환된 정렬 행렬 : [1 3 5 9]
np_sort() 호출 후 원본 행렬 : [3 1 9 5]
ndarray_sort() 호출 후 반환된 행렬 : None
ndarray_sort() 호출 후 원본 행렬 : [1 3 5 9]


In [28]:
# np.sort(), ndarray.sort() 모두 기본적으로 오름차순 정렬
# 내림차순 정렬 [::-1]

sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬 :', sort_array1_desc)

내림차순으로 정렬 : [9 5 3 1]


In [29]:
# 행렬이 2차원 이상일 경우 axis 값 설정을 통해 정렬 수행

array2d = np.array([[8, 12], 
                    [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬 :\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('칼럼 방향으로 정렬 :\n', sort_array2d_axis1)

로우 방향으로 정렬 :
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 :
 [[ 8 12]
 [ 1  7]]


In [30]:
# 정렬된 행렬의 인덱스 반환하기

org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스: ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스:  [1 0 3 2]


In [31]:
# 내림차순 정렬 시 원본 행렬의 인덱스

org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스: ', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스:  [2 3 0 1]


In [32]:
# argsort() 넘파이의 데이터 추출에서 활용

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스 :', sort_indices_asc)
print('성적 오름차순으로 name_array의 인덱스 :', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 : [0 2 4 1 3]
성적 오름차순으로 name_array의 인덱스 : ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

## 행렬 내적
- np.dot()
- 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 함

In [33]:
A = np.array([[1, 2, 3], 
             [4, 5, 6]]) # 열 개수 2
B = np.array([[7, 8], 
             [9, 10], 
             [11, 12]]) # 행 개수 2

dot_product = np.dot(A, B) # A 행렬과 B 행렬의 곱
print('행렬 내적 결과 :\n', dot_product)

행렬 내적 결과 :
 [[ 58  64]
 [139 154]]


## 전치 행렬
- 원 행렬의 행과 열 위치를 교환한 원소로 구성한 행렬
- transpose()

In [34]:
A = np.array([[1, 2], 
             [3, 4]])

transpose_mat = np.transpose(A)
print('A의 전치 행렬 :\n', transpose_mat)

A의 전치 행렬 :
 [[1 3]
 [2 4]]
