# numpy

### 넘파이 ndarray의 개요 

In [4]:
import numpy as np #넘파이 모듈 import

In [7]:
array1 = np.array([1,2,3]) #array함수는 파이썬의 다양한 인자를 받아서 ndarray로 변환함.
print('array1 type:', type(array1)) 
print('array1의 형태', array1.shape)

array2 = np.array([[1,2,3], [2,3,4]])
print('array2 type:', type(array2))
print('array2의 형태', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3의 형태', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1의 형태 (3,)
array2 type: <class 'numpy.ndarray'>
array2의 형태 (2, 3)
array3 type: <class 'numpy.ndarray'>
array3의 형태 (1, 3)


**여기서 또한 중요한 것은 axis번호가 부여되는 방식이다.**

**행에게 가장 높은 숫자, 그 다음 낮은 숫자는 열에게, 그리고 그다음 생성된 차원에게 번호를 부여하는 방식이다.** 

**3차원 배열을 예시로 보자면 행에게 axis2를, 열에게 axis1을 그 다음 생성된 축에게 axis0을 부여한다.**
*->(axis0,axis1,axis2)

In [8]:
print(f'array1: {array1.ndim}차원, array2: {array2.ndim}차원, array3: {array3.ndim}차원') #ndim은 차원 확인

array1: 1차원, array2: 2차원, array3: 2차원


### ndarray의 데이터 타입

In [12]:
list1 = [1,2,3]
print(list1, type(list1))

array1=np.array(list1)
print(array1, type(array1))
print(array1.dtype) #dtype은 ndarray 내의 데이터값의 타입을 알려준다.

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>
int32


In [15]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2, 3.2]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1.  2.  3.2] float64


데이터 타입이 모두 같은 데이터여야 하므로 비교 했을 때 데이터 타입이 더 작은 것이 더 큰 데이터 타입으로 변환되어 dtype값을 나타낸다.

In [16]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


astype 메소드를 이용해서 데이터 값의 타입을 변경할 수 있다.

### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [17]:
sequence_array= np.arange(10)
print(sequence_array, type(sequence_array))
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
int32 (10,)


arange는 파이썬의 range와 비슷하게 start, stop인자값을 부여하여 연속 숫자 값의 ndarray를 생성해줌.

In [18]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


zeros()는 shape값을 인자로 받고 모든 값을 0으로 채운 해당 shape를 가진 ndarray반환

ones()는 zeros와 비슷하게 1로 채운다. 이떄 dtype값을 정해주지 않으면 default로 float형으로 반환.

### ndarray의 차원과 크기를 변경하는 reshape()

In [19]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
array1.reshape(4,3) #지정된 사이즈로 변경이 불가능할 때는 오류

ValueError: cannot reshape array of size 10 into shape (4,3)

In [21]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


-1을 인자로 사용할 경우 ndarray와 호환되는 새로운 shape으로 반환

In [22]:
array1=np.arange(10)
array4=array1.reshape(-1,4) #당연하게 호환되는게 없으니 오류

ValueError: cannot reshape array of size 10 into shape (4)

In [23]:
array1 = np.arange(8)
array3d = array1.reshape(2, 2, 2) 
print('array3d:\n', array3d.tolist()) #tolist메소드는 ndarray를 list로 변환함.(시각적으로 list가 더 보기 편함)

array5 = array3d.reshape(-1, 1) # 3차원 -> 2차원
print('array5:\n', array5.tolist())
print('array5 shape:\n', array5.shape)

array6 = array1.reshape(-1,1)#1차원 -> 2차원
print('array6:\n', array6.tolist())
print('array6 shape:\n', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape:
 (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape:
 (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)

In [25]:
# 1부터 9까지 1차원 ndarray 생성
array1 = np.arange(1,10)
print('array1:', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))
print(array1.dtype)

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
int32


In [26]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [27]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [28]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


### 슬라이싱

In [29]:
array1 = np.arange(1,10)
array3 = array1[0:3] #슬라이싱도 배열과 똑같이 시작이 0
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [30]:
array1 = np.arange(1,10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [31]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [32]:
print(array2d[0]) 
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### 팬시 인덱싱

In [35]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1], 2] #한 축 안에 있는 대괄호는 2차원 배열의 원리로 작동하는게 아니라 그냥 지정한 인덱스의 집합이다.
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]] #axis0에 있는 0배열과 1번 배열을 말하는 것이다.
print('array2d[[0,1]] => ',array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱

In [52]:
array1d = np.arange(1,10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [53]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [54]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [55]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()

In [57]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)

sort_array1 = np.sort(org_array)#반환값o, 원본 행렬은 그대로     
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# np.sort()의 경우 원본 행렬을 인자로 받아 

sort_array2 = org_array.sort() #반환값x, 원본 행렬을 정렬
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2) 
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [59]:
sort_array1_desc = np.sort(org_array)[::-1] #내림차순으로 정렬, 기존 sort방식에 [::-1]만 추가
print ('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [60]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [61]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array) #오름차순으로 정렬 후, 기존 원본 행렬의 원소에 대한 인덱스를 반환
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


[3 1 9 5] -> [1 3 5 9]

 0 1 2 3 ->        1 0 3 2

In [64]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1] #argsort를 내림차순으로
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [65]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


이런 식으로 시험 성적순으로 학생 이름을 출력하고자 할 때 사용할 수 있다

### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [66]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [67]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
