# Ch01. 파이썬 기반의 머신러닝과 생태계 이해

## 3. 넘파이

### Numpy ndarray 개요
- 넘파이의 기반 데이터 타입은 ndarrray
- 다차원 배열 생성, 다양한 연산 수행

In [2]:
# 넘파이 모듈 임포트
import numpy as np

- **np.array()**: 객체를 인자로 입력하면 ndarray로 반환
- **ndarray.shape**: ndarray의 행과 열의 수를 튜플 형태로 저장
- **ndarray.ndim**: ndarray의 차원

In [3]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1)) # 타입: ndarray
print('array1 array 형태:', array1.shape) # 1차원 array, 데이터가 3개

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type:', type(array2)) # 타입: ndarray
print('array2 array 형태:', array2.shape) # 2차원 array, row: 2개, col: 3개

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3)) # 타입: ndarray
print('array3 array 형태:', array3.shape) # 2차원 array, row: 1개, col: 3개

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [4]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


### ndarray의 데이터 타입
- ndarray 내의 데이터값은 숫자 값, 문자열 값, 불 값 등 모두 가능
- ndarray 내에서 같은 데이터 타입만 가능

- **ndarray.dtype**: ndarray 내의 데이터 타입
- 다른 데이터 유형이 섞인 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환
- **ndarray.astype()**: ndarray 내의 데이터 타입 변경, 인자로 원하는 타입을 문자열로 지정

In [5]:
list1 = [1, 2, 3]
print(type(list1)) # 타입: list
array1 = np.array(list1)
print(type(array1)) # 타입: ndarray
print(array1, array1.dtype) # 데이터 타입: int형

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [6]:
list2 = [1, 2, 'test'] # list2: int형 + 문자열
array2 = np.array(list2)
print(array2, array2.dtype) # 데이터 타입: 유니코드 문자열

list3 = [1, 2, 3.0] # list3: int형 + float형
array3 = np.array(list3)
print(array3, array3.dtype) # 데이터 타입: float형

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [7]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64') # float형으로 변환
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32') # int형으로 변환
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32') # float형을 int형으로 변경할 때 소수점 이하는 버림
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones
- 주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화할 경우에 사용

- **np.arange()**: 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray 값으로 변환 (start 값도 부여해 다른 값부터 시작한 연속 값 부여 가능)
- **np.zeros()**: 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 **0**으로 채운 ndarray를 반환
- **np.ones()**: 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 **1**으로 채운 ndarray를 반환
- 디폴트는 flaot64형, 함수 인자로 dtype을 정해줄 수 있음

In [8]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape) # 데이터 타입: int형, 데이터가 10개인 1차원 array

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [9]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape) # 데이터 타입: int형, row: 3개, col: 2개

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape) # 데이터 타입: float형, row: 3개, col: 2개

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()
- **ndarray.reshape()**: ndarray를 함수 인자로 부여한 특정 차원 및 크기로 변환
- -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환
- reshape(-1, 1)은 각각의 ndarray를 2차원으로 형태를 통일할 때 유용하게 사용
- **ndarray.tolist()**: ndarray를 list 자료형으로 변환

In [10]:
array1 = np.arange(10) # array1: 0~9까지의 1차원 array
print('array1:\n', array1)

array2 = array1.reshape(2, 5) # array1을 2*5의 2차원 array로 변환
print('array2:\n', array2)

array3 = array1.reshape(5, 2) # array1을 5*2의 2차원 array로 변환
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1.reshape(4, 3) # 지정된 사이즈로 변경이 불가능하므로 오류 발생

ValueError: cannot reshape array of size 10 into shape (4,3)

In [12]:
array1 = np.arange(10) # 1차원 array, 0~9
print(array1)

array2 = array1.reshape(-1,5) # 고정된 5개의 칼럼에 맞게 2*5의 2차원 array로 reshape
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1) # 고정된 5개의 로우에 맞게 5*2의 2차원 array로 reshape
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [13]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) # 10개의 1차원 데이터를 고정된 4개의 칼럼을 가진 로우로 변경 불가능

ValueError: cannot reshape array of size 10 into shape (4)

In [14]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2)) # 3차원 array
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape) # row: 8개, col: 1개

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape) # row: 8개, col: 1개

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
1) 단일 값 추출
   - 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환
   - 단일 인덱스를 이용해 ndarray 내의 데이터 값 수정 가능
   - 2차원 ndarray에서의 데이터 접근은 콤마(,)로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근
   - 넘파이의 다차원 ndarray는 axis 구분을 가짐(로우: axis 0, 칼럼: axis 1)
   - 축 기반 연산에서 axis가 생략되면 axis 0을 의미

In [15]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value) # 3
print(type(value)) # 데이터 타입: int형

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [16]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2]) # 9, 8

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [17]:
array1[0] = 9 # 0번째 인덱스 위치의 데이터 값을 9로 수정
array1[8] = 0 # 8번째 인덱스 위치의 데이터 값을 0로 수정
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [18]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0]) # 1
print('(row=0,col=1) index 가리키는 값:', array2d[0,1]) # 2
print('(row=1,col=0) index 가리키는 값:', array2d[1,0]) # 4
print('(row=2,col=2) index 가리키는 값:', array2d[2,2]) # 9

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


2) 슬라이싱
   - 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환
   - 시작/종료 인덱스 생략 가능

In [19]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3)) # 타입: ndarray

[1 2 3]
<class 'numpy.ndarray'>


In [20]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3] # 시작 인덱스를 생략하면 맨 처음 인덱스로 간주
print(array4)

array5 = array1[3:] # 종료 인덱스를 생략하면 맨 마지막 인덱스로 간주
print(array5)

array6 = array1[:] # 시작/종료 인덱스를 생략하면 맨 처음/맨 마지막 인덱스로 간주
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [21]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0]) # 로우 축 한쪽에만 슬라이싱을 적용하고, 칼럼 충에는 단일 값 인덱스를 적용

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [22]:
# 2차원에서 뒤에 오는 인덱스를 없애면 1차원 array를 반환
# 3차원에서 뒤에 오는 인덱스를 없애면 2차원 array를 반환

print(array2d[0]) # 로우 축(axis 0)의 첫 번째 로우 ndarray를 반환
print(array2d[1]) # 로우 축(axis 0)의 두 번째 로우 ndarray를 반환
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


3) 팬시 인덱싱
   - 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환

In [23]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2] # (0,2), (1,2)
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2] # ((0,0), (0,1)), ((1,0), (1,1))
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]] # ((0,:), (1,:))
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


4) 불린 인덱싱
   - True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환
   - ndarray의 필터링 조건을 []안에 기재하면 True 값에 해당하는 **인덱스값** 데이터 세트로 ndarray 조회 

In [24]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [25]:
array1d > 5 # ndarray 객체에 조건식을 할당하면 True/False로 이루어진 ndarray 객체를 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [26]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes] # True 값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 반환
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [27]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()
1) 행렬 정렬
   - **np.sort()**: 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
   - **ndarray.sort()**: 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None
   - 기본적으로 오름차순으로 행렬 내 원소 정렬, 내림차순으로 정렬할 경우 [::-1]을 적용
   - 행렬이 2차원 이상일 경우, axis 축 값 설정을 통해 로우/칼럼 방향으로 정렬 수행

In [28]:
org_array = np.array([3, 1, 9, 5]) 
print('원본 행렬:', org_array)
# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2) # None
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [29]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


In [30]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


2) 정렬된 행렬의 인덱스를 반환하기
   - **np.argsort()**: 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [31]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices)) # 타입: ndarray
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [32]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [33]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc]) # 시험 성적 순으로 반환된 인덱스를 name_array에 팬시 인덱스로 적용해 추출

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기
1) 행렬 내적(행렬 곱)
   - **np.dot()**

In [34]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


2) 전치 행렬
   - **np.transpose()**

In [35]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
