# 1-3. Numpy

Numpy: 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지, 빠른 배열 연산 속도가 특징

### **1) Numpy ndarray 개요**

In [ ]:
import numpy as np

In [ ]:
# array(): 리스트 등의 인자를 ndarray로 변환
# shape: 행과 열의 수 (튜플)

array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)
# 1차원, (3, )

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)
# 2차원, (2, 3)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)
# 2차원, (1, 3)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


### **2) ndarray의 데이터 타입**

- 한 개의 ndarray 객체에는 같은 데이터 타입만 있을 수 있음

In [ ]:
# dtype: ndarray의 데이터 타입

list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


- 데이터 유형이 섞여 있는 경우, 데이터 크기가 더 큰 데이터 타입으로 형 변환 적용

In [ ]:
# int형 + 문자열 -> 문자열
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

# int형 + float형 -> float형
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


- 메모리 절약 위해 데이터 타입 변경 (ex. float -> int)

In [ ]:
# astype(): 데이터 타입 변경

# int -> float
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# float -> int
array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

# float -> int
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### **3) ndarray를 편리하게 생성하기 - arange, zeros, ones**

- 연속값 / 0 / 1로 구성된 데이터 생성: 테스트용 데이터 생성, 대규모 데이터 초기화에 사용

In [ ]:
# arrange(): 0(defalut start값)부터 함수 인자 값(stop값) -1까지의 값으로 구성된 ndarray 반환

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
# zeros(): 함수 인자로 튜플 형태의 shape 입력 -> 모든 값을 0으로 채운 해당 shape의 ndarray 반환
# ones(): 모든 값을 1로 채운 ndarray 반환

zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)
# dtype defalut값: float64

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### **4) ndarray의 차원과 크기를 변경하는 reshape()**

In [ ]:
# reshape(): ndarray를 함수 인자 shape로 변환

# [0 1 2 3 4 5 6 7 8 9] 생성
array1 = np.arange(10)
print('array1:\n', array1)

# 2행 5열로 변환
array2 = array1.reshape(2,5)
print('array2:\n',array2)

# 5행 2열로 변환
array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- 지정된 shape로 변경이 불가능하면 오류 발생

In [ ]:
array1.reshape(4,3)
# (10, )을 (4, 3)으로 변경 불가능

ValueError: cannot reshape array of size 10 into shape (4,3)

- -1 인자: 고정된 데이터 개수, 로우/칼럼 개수와 호환될 수 있는 칼럼/로우 개수를 자동으로 인식 후 ndarray 반환

In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)
# 10개의 데이터, 5개의 칼럼과 호환될 수 있는 로우 개수: 2개

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)
# 10개의 데이터, 5개의 로우와 호환될 수 있는 칼럼 개수: 2개

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


- -1 인자 역시 호환될 수 있는 경우가 없다면 오류 발생

In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)
# 10개의 데이터, 4개의 칼럼과 호환죌 수 있는 로우 개수는 없음

ValueError: cannot reshape array of size 10 into shape (4)

- reshape(-1, 1) 형태 자주 사용: 칼럼이 1개인 2차원 ndarray로 변환 -> stack이나 concat으로 결합할 때 유용하게 사용

In [ ]:
# tolist(): 리스트로 변환 (ndarray보다 시각적으로 이해하기 쉬워서)

array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 -> 2차원
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 -> 2차원
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### **5) numpy의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)**

1. **단일값 추출**: 원하는 위치의 인덱스 값을 [ ] 안에 입력



In [ ]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [ ]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


- 단일 인덱스 이용해 ndarray 내의 데이터값 수정

In [ ]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


- 2차원 ndarray에서 단일 값 추출: [row(axis 0), col(axis 1)]

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


2. **슬라이싱(Slicing)**: 연속된 데이터 추출, [시작 인덱스:종료 인덱스] 시작 인덱스부터 종료 인덱스 -1까지의 ndarray 반환

In [ ]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


- 시작 및 종료 인덱스의 생략

In [ ]:
# 시작 인덱스 생략 -> 0부터로 간주
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

# 종료 인덱스 생략 -> 마지막 인덱스까지로 간주
array5 = array1[3:]
print(array5)

# 둘다 생략 -> 맨 처음부터 맨 마지막까지로 간주
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


- 2차원 ndarray에서의 슬라이싱 [row 인덱스 범위, col 인덱스 범위]

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


- n차원 ndarray에서 뒤에 오는 인덱스를 없애면 (n-1)차원 ndarray 반환

In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


3. **팬시 인덱싱(fancy indexing)**: 리스트나 ndarray로 인덱스 집합 지정 -> 해당 위치의 인덱스에 해당하는 ndarray 반환

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())
# (0, 2), (1, 2)

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())
# ((0, 0), (0, 1)), ((1, 0), (1, 1))

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())
# ((0, :), (1, :))

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


4. **불린 인덱싱(Boolean indexing)**: [ ] 안에 조건문 작성

In [ ]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


- 불린 인덱싱 동작 단계

1.   array1d > 5 Boolean 조건을 [ ] 안에 입력
2.   True 값에 해당하는 Index 값 저장
3.   저장된 Index 값으로 데이터 조회



In [ ]:
array1d > 5
# Boolean값으로 이뤄진 ndarray 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### **6) 행렬의 정렬 – sort( )와 argsort( )**

1. **행렬 정렬**

- np.sort(): 원 행렬 유지, 정렬된 행렬 반환
- ndarray.sort(): 원 행렬 자체를 변환, 반환값은 None

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort( )로 정렬
sort_array1 = np.sort(org_array)
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


- 행렬이 2차원 이상일 경우:  axis 축 값 설정

In [ ]:
array2d = np.array([[8, 12],
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


2. **정렬 행렬의 인덱스 반환하기**

- np.argsort(): 정렬된 행렬의 원본 행렬 인덱스를 ndarray형으로 반환

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


- argsort() 활용

In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### **7) 선형대수 연산 – 행렬 내적과 전치 행렬 구하기**

1. **행렬 내적(행렬 곱)**

- A, B의 내적 = A의 로우와 B의 칼럼의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값

In [ ]:
#np.dot(): 행렬 내적

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

# dot_product(0, 0) = 1*7 + 2*9 + 3*11
# dot_product(0, 1) = 1*8 + 2*10 + 3*12
# dot_product(1, 0) = 4*7 + 5*9 + 6*11
# dot_product(1, 1) = 4*8 + 5*10 + 6*12

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


2. **전치 행렬**

- 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬

In [ ]:
#np.transpose(): 전치 행렬

A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
