# Numpy ndarray 개요

### 모듈 import

In [5]:
import numpy as np

### array() 함수

파이썬 리스트와 같은 다양한 인자를 입력 받아 ndarray로 변환

In [12]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))

array1 type: <class 'numpy.ndarray'>
array2 type: <class 'numpy.ndarray'>
array3 type: <class 'numpy.ndarray'>


### shape

ndarray의 차원 크기를 튜플 형태로 반환하는 속성 -> 배열의 차원과 해당 차원에 있는 요소의 개수

In [13]:
print('array1 array 형태:',array1.shape) # array1: 1차원, 요소가 3개
print('array2 array 형태:',array2.shape) # array2: 2차원, 2개의 행과 각 행마다 3개의 열
print('array3 array 형태:',array3.shape) # array3: 2차원, 1개의 행과 각 행마다 3개의 열

array1 array 형태: (3,)
array2 array 형태: (2, 3)
array3 array 형태: (1, 3)


### ndim

ndarray의 차원 수를 나타내는 속성

In [3]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


### type() 함수

주어진 객체의 자료형을 반환

In [10]:
#array() 함수를 통해 list를 ndarray로 변경

list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))

<class 'list'>
<class 'numpy.ndarray'>


### dtype

ndarray의 요소의 데이터 타입을 나타내는 속성

In [11]:
print(array1, array1.dtype)

[1 2 3] int32


### 여러 타입의 데이터가 한 array에 포함될 경우

- [문자열, 숫자열] -> 문자열
- [숫자열, 실수형] -> 실수형

In [7]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


### astype() 함수

ndarray의 데이터 타입을 변경하는 메소드

In [6]:
# int -> float
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# float -> int
array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

# float -> int (소수점 버림)
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray를 편리하게 생성하기 - arange, zeros, ones

특정 크기와 차원을 가진 ndarray의 연속값이나 0, 1로 초기화해서 생성할 필요가 있는 경우

## arange()

array를 range()로 표현, 지정된 간격과 범위에 따라 숫자를 생성하여 배열을 생성

**numpy.arange([start,] stop[, step,], dtype=None)**

- start: 배열의 시작값으로, 기본값은 0
- stop: 배열의 끝값으로, 이 값은 배열에 포함되지 않음
- step: 각 요소 사이의 간격을 나타내며, 기본값은 1
- dtype: 배열의 데이터 타입을 나타내며, 기본값은 None이며 자동으로 유추

In [21]:
sequence_array = np.arange(10) # start: 0, stop: 10, step: 1, dtype: 정수형으로 자동으로 유추
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape) # 정수형, 1차원, 요소가 10개

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


## zeros(), ones()

입력한 shape를 0 또는 1로 채운 ndarray 반환

**numpy.zeros(shape, dtype=float, order='C') / numpy.ones(shape, dtype=float, order='C')**

- shape: 생성하려는 배열의 모양(shape)을 나타내는 튜플로, 각 차원의 크기를 지정
- dtype: 배열의 데이터 타입, 기본값은 부동 소수점(float)
- order: 배열 요소가 메모리에 저장되는 순서, 'C' (기본값)는 행 기반 저장을 나타내며 'F'는 열 기반 저장을 나타냄

In [18]:
zero_array = np.zeros((3,2),dtype='int32') # 3x2 모양의 정수형 배열, 모든 요소를 0으로 초기화
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [20]:
one_array = np.ones((3,2)) # 3x2 모양의 실수형 배열, 모든 요소를 1로 초기화
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## reshape() 함수

배열 shape, 즉 형태(차원)을 변경하는 함수

**numpy.reshape(array, new_shape, order='C')**

- array: 형태를 변경하려는 배열
- new_shape: 변경하려는 배열의 모양(shape)을 나타내는 튜플로, 각 차원의 크기를 지정
- order: 배열 요소가 메모리에 저장되는 순서, 'C' (기본값)는 행 기반 저장을 나타내며 'F'는 열 기반 저장을 나타냄

In [22]:
array1 = np.arange(10)
print('array1:\n', array1)

# array1의 형태를 (2, 5)로 변경, 2개의 행, 5개의 열
array2 = array1.reshape(2,5)
print('array2:\n',array2)

# array1의 형태를 (5, 2)로 변경, 5개의 행, 2개의 열
array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**사이즈 변경이 불가능하면 오류 발생**

In [23]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

### reshape()에서 -1 인자 사용

NumPy가 해당 차원의 크기를 자동으로 계산하여 배열의 형태를 조정

In [24]:
array1 = np.arange(10)
print(array1)

# array1의 형태를 (n, 5)로 변경, 첫 번째 차원의 크기는 -1로 지정되었으므로 해당 차원의 크기를 자동으로 2로 계산
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

# array1의 형태를 (5, n)로 변경, 두 번째 차원의 크기는 -1로 지정되었으므로 해당 차원의 크기를 자동으로 2로 계산
array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


**-1 인자로도 호환될 수 없는 형태로는 호환 불가**

In [26]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) # array1에 있는 10개의 요소를 4개의 열로 나누어 배치할 수 없기 때문에 오류 발생

ValueError: cannot reshape array of size 10 into shape (4)

**-1 인자는 reshape(-1, 1)와 같은 형태로 자주 사용됨**

In [27]:
array1 = np.arange(8)

# 1차원 배열 array1을 (2, 2, 2) 형태의 3차원 배열로 변경
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# array3d 배열을 각 행이 1개의 열을 가진 2차원 배열로 변경, -1을 사용하여 2차원으로 자동 계산
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 배열 array1을 각 행이 1개의 열을 가진 2차원 배열로 변경, -1을 사용하여 2차원으로 자동 계산
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


# indexing

### 단일값 추출

한 개의 데이터만 추출

0부터 시작하는 인덱스를 사용하여 요소에 접근

In [29]:
# 1에서부터 9까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


**음수 인덱싱**

배열의 끝에서부터 요소에 접근 가능

In [ ]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

**단일값을 이용한 데이터 수정**

In [ ]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

**다차원 ndarray에서 단일값 추출**

[행, 열] -> 각각 0부터 시작, 생략하면 0으로 설정

In [32]:
array1d = np.arange(start=1, stop=10) # [1, 2, 3, 4, 5, 6, 7, 8, 9]
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] ) # 0번째 행, 0번째 열
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] ) # 0번째 행, 1번째 열
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] ) # 1번째 행, 0번째 열
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] ) # 2번째 행, 2번째 열

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


### Slicing

**sequence[start:stop:step]**

- start: 추출을 시작할 인덱스로, 이 인덱스에 해당하는 요소는 포함됨
- stop: 추출을 종료할 인덱스로, 이 인덱스에 해당하는 요소는 포함되지 않음
- step: 추출할 요소 사이의 간격을 지정, 기본값은 1

In [ ]:
array1 = np.arange(start=1, stop=10) # [1, 2, 3, 4, 5, 6, 7, 8, 9]

# 0번째 인덱스부터 2번째 인덱스까지 잘라냄 -> [1, 2, 3]
array3 = array1[0:3]
print(array3)

슬라이싱한 결과의 타입은 슬라이싱한 대상의 타입과 동일

In [40]:
print(type(array3))

<class 'numpy.ndarray'>


- start를 생략하는 경우: 시작 인덱스는 배열의 0번째 인덱스부터 시작
- stop를 생략하는 경우: 종료 인덱스는 배열의 마지막 인덱스까지 포함

In [39]:
array1 = np.arange(start=1, stop=10) # [1, 2, 3, 4, 5, 6, 7, 8, 9]

# start를 생략 -> 배열의 0번째 인덱스부터 2번째 인덱스까지 잘라냄
array4 = array1[:3]
print(array4)

# stop을 생략 -> 배열의 3번째 인덱스부터 마지막 인덱스까지 잘라냄
array5 = array1[3:]
print(array5)

# start와 stop을 둘 다 생략 -> 전체 배열를 슬라이싱하는 것과 동일한 결과, 즉 처음부터 끝까지의 모든 요소를 포함
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


**2차원 ndarray에서 인덱싱/슬라이싱**

In [42]:
array1d = np.arange(start=1, stop=10) # [1, 2, 3, 4, 5, 6, 7, 8, 9]
array2d = array1d.reshape(3,3) # 2차원의 3x3 배열로 변경
print('array2d:\n',array2d)

# array2d의 0부터 1번째 행과 0부터 1번째 열에 해당하는 요소를 출력
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])

# array2d의 1부터 2번째 행과 0부터 2번째 열에 해당하는 요소를 출력
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])

# array2d의 1부터 2번째 행 전체와 모든 열에 해당하는 요소를 출력
print('array2d[1:3, :] \n', array2d[1:3, :])

# array2d 전체를 출력
print('array2d[:, :] \n', array2d[:, :])

# array2d의 0부터 1번째 행과 1번째 열부터 마지막 열까지에 해당하는 요소를 출력
print('array2d[:2, 1:] \n', array2d[:2, 1:])

# array2d의 0부터 1번째 행과 0번째 열에 해당하는 요소를 출력
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


**2차원 배열에서 특정 행을 추출**

해당 행의 모든 열을 포함하는 1차원 배열을 반환

In [43]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### fancy indexing

ndarray에서 특정한 인덱스 집합에 해당하는 요소들을 **한 번에** 선택하는 기법

슬라이싱과 달리, 배열의 **특정 위치나 패턴**에 대한 요소를 선택할 때 사용

In [44]:
array1d = np.arange(start=1, stop=10) # [1, 2, 3, 4, 5, 6, 7, 8, 9]
array2d = array1d.reshape(3,3) # 2차원의 3x3 배열로 변경

# array2d의 0번째 행과 1번째 행에서 열 인덱스가 2인 요소들을 추출
array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

# array2d의 0번째 행과 1번째 행에서 열 인덱스가 0부터 1까지인 열의 요소들을 추출
array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

# array2d의 0번째 행과 1번째 행 전체를 추출
array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


### Boolean indexing

ndarray에서 **특정 조건을 만족**하는 요소들을 선택하는 기법

In [48]:
array1d = np.arange(start=1, stop=10) # [1, 2, 3, 4, 5, 6, 7, 8, 9]

# 불린 인덱싱을 사용하여 조건을 만족하는 요소들만 선택
array3 = array1d[array1d > 5]

# 5보다 크다는 조건을 만족하는 요소: 6, 7, 8, 9
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


**불린 인덱스**

In [52]:
# 배열의 각 요소에 대해 5보다 큰지 여부를 판별하는 불린 인덱스를 생성
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

**불린 인덱스를 사용하여 배열 필터링**

True에 해당하는 위치의 요소들만 선택하여 새로운 배열을 생성

In [55]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])

# 불린 인덱스를 사용하여 True에 해당하는 위치의 요소들만 필터링
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


**일반 인덱스를 사용하여 배열 필터링**

해당 배열에 있는 인덱스에 해당하는 요소들만 선택하여 새로운 배열을 생성

In [54]:
indexes = np.array([5,6,7,8])

# 일반 인덱스를 사용하여 5, 6, 7, 8번째 인덱스에 해당하는 요소들만 필터링
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


# 행렬의 정렬 – sort( )와 argsort( )

## 행렬 정렬

In [56]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)

원본 행렬: [3 1 9 5]


### np.sort( )로 정렬 

**numpy**에서 sort() 함수를 호출, 원본 배열을 변경하지 않고 정렬된 새로운 배열을 반환

In [57]:
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)

np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]


### ndarray.sort( )로 정렬

**배열 객체**의 sort() 메서드를 호출, 배열을 직접 변경

In [59]:
sort_array2 = org_array.sort()

# 배열을 직접 변경하며, 정렬된 배열을 반환하지 않으므로 sort_array2에는 None 값이 저장
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


### 내림차순 정렬

np.sort() 함수의 [::-1] 이용

In [61]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


### 로우 방향, 컬럼 방향으로 정렬 

행렬이 2차원일 경우 aixs 축 값 설정을 통해 가능

In [62]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

# 로우 방향 정렬 : axis=0
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

# 컬럼 방향 정렬 : axis=1
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


## 정렬 행렬의 인덱스 반환

### argsort() 함수

정렬된 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

**오름차순 정렬시**

In [66]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)

print(type(sort_indices)) # ndarray 형
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


**내림차순 정렬시**

In [68]:
org_array = np.array([ 3, 1, 9, 5]) 

sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


**실전 사용 예시**

In [69]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

### 행렬 내적 : dot()

두 개의 행렬을 곱하는 연산

In [70]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### 전치 행렬 : transpose()

행렬의 행과 열을 바꾸는 연산

In [71]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
